In [2]:
import sqlite3
import pandas as pd 

conn = sqlite3.connect("adventureworks_financial_analysis.db")

query = """
SELECT name 
FROM sqlite_master
WHERE type='table'; 
"""

tables = pd.read_sql(query, conn)
tables

                     name
0              DimProduct
1             DimCustomer
2                 DimDate
3            DimGeography
4      DimProductCategory
5   DimProductSubcategory
6       FactInternetSales
7             FactFinance
8          FactSalesQuota
9       DimSalesTerritory
10            DimScenario
11             DimAccount

In [3]:
sales = pd.read_sql(""" 
SELECT * 
FROM FactInternetSales
""", conn)
sales.head()

,ProductKey,OrderDateKey,DueDateKey,ShipDateKey,CustomerKey,PromotionKey,CurrencyKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,...,ExtendedAmount,UnitPriceDiscountPct,DiscountAmount,ProductStandardCost,TotalProductCost,SalesAmount,TaxAmt,Freight,CarrierTrackingNumber,CustomerPONumber
0,310,20050701,20050713,20050708,21768,1,19,6,SO43697,1,...,3578.2700,0.0,0.0,2171.2942,2171.2942,3578.2700,286.2616,89.4568,None,None
1,346,20050701,20050713,20050708,28389,1,39,7,SO43698,1,...,3399.9900,0.0,0.0,1912.1544,1912.1544,3399.9900,271.9992,84.9998,None,None
2,346,20050701,20050713,20050708,25863,1,100,1,SO43699,1,...,3399.9900,0.0,0.0,1912.1544,1912.1544,3399.9900,271.9992,84.9998,None,None
3,336,20050701,20050713,20050708,14501,1,100,4,SO43700,1,...,699.0982,0.0,0.0,413.1463,413.1463,699.0982,55.9279,17.4775,None,None
4,346,20050701,20050713,20050708,11003,1,6,9,SO43701,1,...,3399.9900,0.0,0.0,1912.1544,1912.1544,3399.9900,271.9992,84.9998,None,None

In [4]:
sales.shape

(60398, 23)

In [5]:
sales.info

<bound method DataFrame.info of        ProductKey  OrderDateKey  DueDateKey  ShipDateKey  CustomerKey  \
0             310      20050701    20050713     20050708        21768
1             346      20050701    20050713     20050708        28389
2             346      20050701    20050713     20050708        25863
3             336      20050701    20050713     20050708        14501
4             346      20050701    20050713     20050708        11003
...           ...           ...         ...          ...          ...
60393         485      20080731    20080812     20080807        15868
60394         225      20080731    20080812     20080807        15868
60395         485      20080731    20080812     20080807        18759
60396         486      20080731    20080812     20080807        18759
60397         225      20080731    20080812     20080807        18759

       PromotionKey  CurrencyKey  SalesTerritoryKey SalesOrderNumber  \
0                 1           19                  6          SO43697
1                 1           39                  7          SO43698
2                 1          100                  1          SO43699
3                 1          100                  4          SO43700
4                 1            6                  9          SO43701
...             ...          ...                ...              ...
60393             1          100                  6          SO75122
60394             1          100                  6          SO75122
60395             1          100                  6          SO75123
60396             1          100                  6          SO75123
60397             1          100                  6          SO75123

       SalesOrderLineNumber  ...  ExtendedAmount  UnitPriceDiscountPct  \
0                         1  ...       3578.2700                   0.0
1                         1  ...       3399.9900                   0.0
2                         1  ...       3399.9900                   0.0
3                         1  ...        699.0982                   0.0
4                         1  ...       3399.9900                   0.0
...                     ...  ...             ...                   ...
60393                     1  ...         21.9800                   0.0
60394                     2  ...          8.9900                   0.0
60395                     1  ...         21.9800                   0.0
60396                     2  ...        159.0000                   0.0
60397                     3  ...          8.9900                   0.0

       DiscountAmount  ProductStandardCost  TotalProductCost  SalesAmount  \
0                 0.0            2171.2942         2171.2942    3578.2700
1                 0.0            1912.1544         1912.1544    3399.9900
2                 0.0            1912.1544         1912.1544    3399.9900
3                 0.0             413.1463          413.1463     699.0982
4                 0.0            1912.1544         1912.1544    3399.9900
...               ...                  ...               ...          ...
60393             0.0               8.2205            8.2205      21.9800
60394             0.0               6.9223            6.9223       8.9900
60395             0.0               8.2205            8.2205      21.9800
60396             0.0              59.4660           59.4660     159.0000
60397             0.0               6.9223            6.9223       8.9900

         TaxAmt  Freight  CarrierTrackingNumber  CustomerPONumber
0      286.2616  89.4568                   None              None
1      271.9992  84.9998                   None              None
2      271.9992  84.9998                   None              None
3       55.9279  17.4775                   None              None
4      271.9992  84.9998                   None              None
...         ...      ...                    ...               ...
60393    1.7584   0.5495                   None              None
60394    0.7192   0.2248                   None              None
60395    1.7584   0.5495                   None              None
60396   12.7200   3.9750                   None              None
60397    0.7192   0.2248                   None              None

[60398 rows x 23 columns]>

In [6]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 60398 entries, 0 to 60397
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ProductKey             60398 non-null  int64
 1   OrderDateKey           60398 non-null  int64
 2   DueDateKey             60398 non-null  int64
 3   ShipDateKey            60398 non-null  int64
 4   CustomerKey            60398 non-null  int64
 5   PromotionKey           60398 non-null  int64
 6   CurrencyKey            60398 non-null  int64
 7   SalesTerritoryKey      60398 non-null  int64
 8   SalesOrderNumber       60398 non-null  str
 9   SalesOrderLineNumber   60398 non-null  int64
 10  RevisionNumber         60398 non-null  int64
 11  OrderQuantity          60398 non-null  int64
 12  UnitPrice              60398 non-null  float64
 13  ExtendedAmount         60398 non-null  float64
 14  UnitPriceDiscountPct   60398 non-null  float64
 15  DiscountAmount         60398 non-null  float64
 16  ProductStandardCost    60398 non-null  float64
 17  TotalProductCost       60398 non-null  float64
 18  SalesAmount            60398 non-null  float64
 19  TaxAmt                 60398 non-null  float64
 20  Freight                60398 non-null  float64
 21  CarrierTrackingNumber  0 non-null      object
 22  CustomerPONumber       0 non-null      object
dtypes: float64(9), int64(11), object(2), str(1)
memory usage: 10.6+ MB

In [7]:
sales.describe

<bound method NDFrame.describe of        ProductKey  OrderDateKey  DueDateKey  ShipDateKey  CustomerKey  \
0             310      20050701    20050713     20050708        21768
1             346      20050701    20050713     20050708        28389
2             346      20050701    20050713     20050708        25863
3             336      20050701    20050713     20050708        14501
4             346      20050701    20050713     20050708        11003
...           ...           ...         ...          ...          ...
60393         485      20080731    20080812     20080807        15868
60394         225      20080731    20080812     20080807        15868
60395         485      20080731    20080812     20080807        18759
60396         486      20080731    20080812     20080807        18759
60397         225      20080731    20080812     20080807        18759

       PromotionKey  CurrencyKey  SalesTerritoryKey SalesOrderNumber  \
0                 1           19                  6          SO43697
1                 1           39                  7          SO43698
2                 1          100                  1          SO43699
3                 1          100                  4          SO43700
4                 1            6                  9          SO43701
...             ...          ...                ...              ...
60393             1          100                  6          SO75122
60394             1          100                  6          SO75122
60395             1          100                  6          SO75123
60396             1          100                  6          SO75123
60397             1          100                  6          SO75123

       SalesOrderLineNumber  ...  ExtendedAmount  UnitPriceDiscountPct  \
0                         1  ...       3578.2700                   0.0
1                         1  ...       3399.9900                   0.0
2                         1  ...       3399.9900                   0.0
3                         1  ...        699.0982                   0.0
4                         1  ...       3399.9900                   0.0
...                     ...  ...             ...                   ...
60393                     1  ...         21.9800                   0.0
60394                     2  ...          8.9900                   0.0
60395                     1  ...         21.9800                   0.0
60396                     2  ...        159.0000                   0.0
60397                     3  ...          8.9900                   0.0

       DiscountAmount  ProductStandardCost  TotalProductCost  SalesAmount  \
0                 0.0            2171.2942         2171.2942    3578.2700
1                 0.0            1912.1544         1912.1544    3399.9900
2                 0.0            1912.1544         1912.1544    3399.9900
3                 0.0             413.1463          413.1463     699.0982
4                 0.0            1912.1544         1912.1544    3399.9900
...               ...                  ...               ...          ...
60393             0.0               8.2205            8.2205      21.9800
60394             0.0               6.9223            6.9223       8.9900
60395             0.0               8.2205            8.2205      21.9800
60396             0.0              59.4660           59.4660     159.0000
60397             0.0               6.9223            6.9223       8.9900

         TaxAmt  Freight  CarrierTrackingNumber  CustomerPONumber
0      286.2616  89.4568                   None              None
1      271.9992  84.9998                   None              None
2      271.9992  84.9998                   None              None
3       55.9279  17.4775                   None              None
4      271.9992  84.9998                   None              None
...         ...      ...                    ...               ...
60393    1.7584   0.5495                   None              None
60394    0.7192   0.2248                   None              None
60395    1.7584   0.5495                   None              None
60396   12.7200   3.9750                   None              None
60397    0.7192   0.2248                   None              None

[60398 rows x 23 columns]>

In [8]:
sales.describe()

,ProductKey,OrderDateKey,DueDateKey,ShipDateKey,CustomerKey,PromotionKey,CurrencyKey,SalesTerritoryKey,SalesOrderLineNumber,RevisionNumber,OrderQuantity,UnitPrice,ExtendedAmount,UnitPriceDiscountPct,DiscountAmount,ProductStandardCost,TotalProductCost,SalesAmount,TaxAmt,Freight
count,60398.000000,6.039800e+04,6.039800e+04,6.039800e+04,60398.000000,60398.000000,60398.000000,60398.000000,60398.000000,60398.0,60398.0,60398.000000,60398.000000,60398.0,60398.0,60398.000000,60398.000000,60398.000000,60398.000000,60398.000000
mean,437.557932,2.007522e+07,2.007557e+07,2.007543e+07,18841.685420,1.041839,69.845326,6.244462,1.886321,1.0,1.0,486.086911,486.086911,0.0,0.0,286.065657,286.065657,486.086911,38.886954,12.152217
std,118.088390,6.394891e+03,6.341781e+03,6.368323e+03,5432.430404,0.342605,42.146363,2.961150,1.016328,0.0,0.0,928.489892,928.489892,0.0,0.0,552.457641,552.457641,928.489892,74.279193,23.212248
min,214.000000,2.005070e+07,2.005071e+07,2.005071e+07,11000.000000,1.000000,6.000000,1.000000,1.000000,1.0,1.0,2.290000,2.290000,0.0,0.0,0.856500,0.856500,2.290000,0.183200,0.057300
25%,359.000000,2.007100e+07,2.007102e+07,2.007101e+07,14003.000000,1.000000,19.000000,4.000000,1.000000,1.0,1.0,7.950000,7.950000,0.0,0.0,2.973300,2.973300,7.950000,0.636000,0.198800
50%,479.000000,2.008012e+07,2.008013e+07,2.008012e+07,18143.000000,1.000000,100.000000,7.000000,2.000000,1.0,1.0,29.990000,29.990000,0.0,0.0,11.216300,11.216300,29.990000,2.399200,0.749800
75%,529.000000,2.008042e+07,2.008050e+07,2.008043e+07,23429.750000,1.000000,100.000000,9.000000,2.000000,1.0,1.0,539.990000,539.990000,0.0,0.0,294.579700,294.579700,539.990000,43.199200,13.499800
max,606.000000,2.008073e+07,2.008081e+07,2.008081e+07,29483.000000,14.000000,100.000000,10.000000,8.000000,1.0,1.0,3578.270000,3578.270000,0.0,0.0,2171.294200,2171.294200,3578.270000,286.261600,89.456800

In [9]:
sales["SalesAmount"].sum()

np.float64(29358677.220699992)

In [10]:
sales(["SalesAmount"].mean(), 2)

AttributeError: 'list' object has no attribute 'mean'

In [11]:
round(sales["SalesAmount"].mean(), 2)

np.float64(486.09)

In [12]:
sales["SalesAmount"].max,()

(<bound method Series.max of 0        3578.2700
 1        3399.9900
 2        3399.9900
 3         699.0982
 4        3399.9900
            ...
 60393      21.9800
 60394       8.9900
 60395      21.9800
 60396     159.0000
 60397       8.9900
 Name: SalesAmount, Length: 60398, dtype: float64>,
 ())

In [13]:
sales["SalesAmount"].max()

np.float64(3578.27)

In [14]:
sales["SalesAmount"].unique()

array([3.5782700e+03, 3.3999900e+03, 6.9909820e+02, 3.3749900e+03,
       1.0004375e+03, 2.1815625e+03, 7.8299000e+02, 2.0490982e+03,
       2.0714196e+03, 2.4433500e+03, 8.9900000e+00, 1.2148500e+03,
       3.4990000e+01, 2.3199900e+03, 9.9900000e+00, 4.9900000e+00,
       3.2600000e+01, 3.9900000e+00, 1.5900000e+02, 4.9990000e+01,
       1.7009900e+03, 3.5000000e+01, 7.4235000e+02, 2.8990000e+01,
       2.3840700e+03, 5.3999000e+02, 2.1490000e+01, 2.4490000e+01,
       2.4990000e+01, 2.2949900e+03, 2.1980000e+01, 7.6949000e+02,
       2.9990000e+01, 1.1204900e+03, 5.3990000e+01, 5.6499000e+02,
       2.2900000e+00, 5.4990000e+01, 6.3500000e+01, 7.9500000e+00,
       1.2000000e+02, 6.9990000e+01])

In [15]:
sales["SalesorderNumber"].nunique()

KeyError: 'SalesorderNumber'

In [16]:
sales["SalesOrderNumber"].nunique()

27659

In [17]:
sales["CustomerKey"].nunique()

18484

In [18]:
sales["SalesOrderNumer"].nunique() / sales["CustomerKey"].nunique()

KeyError: 'SalesOrderNumer'

In [19]:
sales["SalesOrderNumber"].nunique() / sales["CustomerKey"].nunique()

1.4963752434537978

In [20]:
sales["OrderQuantity"].sum()

np.int64(60398)

In [21]:
sales["SalesAmount"].sum() / sales["OrderQuantity"].nunique()

np.float64(29358677.220699992)

In [22]:
sales["TotalProductCost"].sum()

np.float64(17277793.5757)

In [23]:
sales["SalesAmount"].sum() - sales["TotalProductCost"].sum()

np.float64(12080883.644999992)

In [24]:
(
    (sales["SalesAmount"].sum() - sales["TotalProductCost"].sum())
    / sales["SalesAmount"].sum()
) *100

np.float64(41.14927778994789)

In [25]:
dates = pd.read_sql("""
SELECT *
FROM DimDate
""", conn)

dates.head()

,DateKey,FullDateAlternateKey,DayNumberOfWeek,EnglishDayNameOfWeek,SpanishDayNameOfWeek,FrenchDayNameOfWeek,DayNumberOfMonth,DayNumberOfYear,WeekNumberOfYear,EnglishMonthName,SpanishMonthName,FrenchMonthName,MonthNumberOfYear,CalendarQuarter,CalendarYear,CalendarSemester,FiscalQuarter,FiscalYear,FiscalSemester
0,20050701,2005-07-01,6,Friday,Viernes,Vendredi,1,182,27,July,Julio,Juillet,7,3,2005,2,1,2006,1
1,20050702,2005-07-02,7,Saturday,Sábado,Samedi,2,183,27,July,Julio,Juillet,7,3,2005,2,1,2006,1
2,20050703,2005-07-03,1,Sunday,Domingo,Dimanche,3,184,27,July,Julio,Juillet,7,3,2005,2,1,2006,1
3,20050704,2005-07-04,2,Monday,Lunes,Lundi,4,185,27,July,Julio,Juillet,7,3,2005,2,1,2006,1
4,20050705,2005-07-05,3,Tuesday,Martes,Mardi,5,186,27,July,Julio,Juillet,7,3,2005,2,1,2006,1

In [26]:
dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 1188 entries, 0 to 1187
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   DateKey               1188 non-null   int64
 1   FullDateAlternateKey  1188 non-null   str
 2   DayNumberOfWeek       1188 non-null   int64
 3   EnglishDayNameOfWeek  1188 non-null   str
 4   SpanishDayNameOfWeek  1188 non-null   str
 5   FrenchDayNameOfWeek   1188 non-null   str
 6   DayNumberOfMonth      1188 non-null   int64
 7   DayNumberOfYear       1188 non-null   int64
 8   WeekNumberOfYear      1188 non-null   int64
 9   EnglishMonthName      1188 non-null   str
 10  SpanishMonthName      1188 non-null   str
 11  FrenchMonthName       1188 non-null   str
 12  MonthNumberOfYear     1188 non-null   int64
 13  CalendarQuarter       1188 non-null   int64
 14  CalendarYear          1188 non-null   int64
 15  CalendarSemester      1188 non-null   int64
 16  FiscalQuarter         1188 non-null   int64
 17  FiscalYear            1188 non-null   int64
 18  FiscalSemester        1188 non-null   int64
dtypes: int64(12), str(7)
memory usage: 176.5 KB

In [27]:
sales_dates = sales.merge(
    dates,
    left_on="OrderDateKey" ,
    right_on="DateKey" ,
    how="left"
)
sales_dates.head()

,ProductKey,OrderDateKey,DueDateKey,ShipDateKey,CustomerKey,PromotionKey,CurrencyKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,...,EnglishMonthName,SpanishMonthName,FrenchMonthName,MonthNumberOfYear,CalendarQuarter,CalendarYear,CalendarSemester,FiscalQuarter,FiscalYear,FiscalSemester
0,310,20050701,20050713,20050708,21768,1,19,6,SO43697,1,...,July,Julio,Juillet,7,3,2005,2,1,2006,1
1,346,20050701,20050713,20050708,28389,1,39,7,SO43698,1,...,July,Julio,Juillet,7,3,2005,2,1,2006,1
2,346,20050701,20050713,20050708,25863,1,100,1,SO43699,1,...,July,Julio,Juillet,7,3,2005,2,1,2006,1
3,336,20050701,20050713,20050708,14501,1,100,4,SO43700,1,...,July,Julio,Juillet,7,3,2005,2,1,2006,1
4,346,20050701,20050713,20050708,11003,1,6,9,SO43701,1,...,July,Julio,Juillet,7,3,2005,2,1,2006,1

In [28]:
sales_dates.shape

(60398, 42)

In [30]:
revenue_by_year = sales_dates.groupby("CalendarYear")["SalesAmount"].sum()

In [31]:
revenue_by_year

CalendarYear
2005    3.266374e+06
2006    6.530344e+06
2007    9.791060e+06
2008    9.770900e+06
Name: SalesAmount, dtype: float64

In [32]:
round(revenue_by_year.pct_change()*100, 2)

CalendarYear
2005      NaN
2006    99.93
2007    49.93
2008    -0.21
Name: SalesAmount, dtype: float64

In [33]:
sales_dates.groupby("CalendarYear")["OrderDateKey"].count()

CalendarYear
2005     1013
2006     2677
2007    24443
2008    32265
Name: OrderDateKey, dtype: int64

In [34]:
sales_dates.groupby("CalendarYear")["EnglishMonthName"].nunique()

CalendarYear
2005     6
2006    12
2007    12
2008     7
Name: EnglishMonthName, dtype: int64

In [35]:
sales_dates.groupby("CalendarYear")["MonthNumberOfYear"].agg(["min", "max", "nunique"])

              min  max  nunique
CalendarYear
2005            7   12        6
2006            1   12       12
2007            1   12       12
2008            1    7        7

In [37]:
monthly_revenue = sales_dates.groupby(
    ["CalendarYear", "MonthNumberOfYear"]
)["SalesAmount"].sum()
monthly_revenue

CalendarYear  MonthNumberOfYear
2005          7                    4.733882e+05
              8                    5.061917e+05
              9                    4.739430e+05
              10                   5.133295e+05
              11                   5.439934e+05
              12                   7.555279e+05
2006          1                    5.967466e+05
              2                    5.508167e+05
              3                    6.441352e+05
              4                    6.636923e+05
              5                    6.735562e+05
              6                    6.767636e+05
              7                    5.003652e+05
              8                    5.460015e+05
              9                    3.504670e+05
              10                   4.153902e+05
              11                   3.350951e+05
              12                   5.773140e+05
2007          1                    4.388652e+05
              2                    4.890903e+05
              3                    4.855748e+05
              4                    5.063993e+05
              5                    5.627726e+05
              6                    5.547992e+05
              7                    8.866688e+05
              8                    8.474135e+05
              9                    1.010258e+06
              10                   1.080450e+06
              11                   1.196981e+06
              12                   1.731788e+06
2008          1                    1.340245e+06
              2                    1.462480e+06
              3                    1.480905e+06
              4                    1.608751e+06
              5                    1.878318e+06
              6                    1.949361e+06
              7                    5.084063e+04
Name: SalesAmount, dtype: float64

In [38]:
sales_dates[
            sales_dates["CalendarYear"] == 2008
] ["DayNumberOfMonth"].max()

np.int64(31)

In [40]:
sales_dates[
    (sales_dates["CalendarYear"] == 2008) &
    (sales_dates["MonthNumberOfYear"] == 7)
]["DayNumberOfMonth"].max()

np.int64(31)

In [41]:
quarterly_revenue = sales_dates.groupby(
    ["CalendarYear", "CalendarQuarter"]
)["SalesAmount"].sum()
quarterly_revenue

CalendarYear  CalendarQuarter
2005          3                  1.453523e+06
              4                  1.812851e+06
2006          1                  1.791698e+06
              2                  2.014012e+06
              3                  1.396834e+06
              4                  1.327799e+06
2007          1                  1.413530e+06
              2                  1.623971e+06
              3                  2.744340e+06
              4                  4.009218e+06
2008          1                  4.283630e+06
              2                  5.436429e+06
              3                  5.084063e+04
Name: SalesAmount, dtype: float64

In [42]:
round(
    quarterly_revenue.pct_change()* 100,
    2
)

CalendarYear  CalendarQuarter
2005          3                    NaN
              4                  24.72
2006          1                  -1.17
              2                  12.41
              3                 -30.64
              4                  -4.94
2007          1                   6.46
              2                  14.89
              3                  68.99
              4                  46.09
2008          1                   6.84
              2                  26.91
              3                 -99.06
Name: SalesAmount, dtype: float64

In [43]:
quarter_table =sales_dates.groupby(
    ["CalendarYear", "CalendarQuarter"]
)["SalesAmount"].sum().unstack()
quarter_table

CalendarQuarter             1             2             3             4
CalendarYear
2005                      NaN           NaN  1.453523e+06  1.812851e+06
2006             1.791698e+06  2.014012e+06  1.396834e+06  1.327799e+06
2007             1.413530e+06  1.623971e+06  2.744340e+06  4.009218e+06
2008             4.283630e+06  5.436429e+06  5.084063e+04           NaN

In [45]:
round(
    ((quarter_table.loc[2008] - quarter_table.loc[2007])
    / quarter_table.loc[2007] * 100,
    2
    )

_IncompleteInputError: incomplete input (524404697.py, line 5)

In [46]:
round(
    ((quarter_table.loc[2008] - quarter_table.loc[2007])
     / quarter_table.loc[2007]) * 100,
    2
)

CalendarQuarter
1    203.04
2    234.76
3    -98.15
4       NaN
dtype: float64

In [47]:
round(
    (
        revenue_by_year.loc[2007]
        - revenue_by_year.loc[2006]
    )
    / revenue_by_year.loc[2006]
    * 100,
    2
)

np.float64(49.93)

In [48]:
orders_by_quarter = sales_dates.groupby(
    ["CalendarYear", "CalendarQuarter"]
)["SalesOrderNumber"].nunique()
orders_by_quarter

CalendarYear  CalendarQuarter
2005          3                   448
              4                   565
2006          1                   558
              2                   635
              3                   732
              4                   752
2007          1                   788
              2                   950
              3                  3695
              4                  5486
2008          1                  5638
              2                  6436
              3                   976
Name: SalesOrderNumber, dtype: int64

In [50]:
orders_by_quarter = sales_dates.groupby(
    ["CalendarYear", "CalendarQuarter"]
)["SalesOrderNumber"].nunique().unstack()
orders_by_quarter

CalendarQuarter       1       2       3       4
CalendarYear
2005                NaN     NaN   448.0   565.0
2006              558.0   635.0   732.0   752.0
2007              788.0   950.0  3695.0  5486.0
2008             5638.0  6436.0   976.0     NaN

In [51]:
round(
    (
        orders_by_quarter.loc[2008]
        - orders_by_quarter.loc[2007]
    )
    / orders_by_quarter.loc[2007]
    * 100,
    2
)

CalendarQuarter
1    615.48
2    577.47
3    -73.59
4       NaN
dtype: float64

In [52]:
sales_dates.groupby("CalendarYear")["CustomerKey"].nunique()

CalendarYear
2005     1013
2006     2677
2007     9309
2008    11377
Name: CustomerKey, dtype: int64

In [53]:
aov_by_quarter = (
    sales_dates.groupby(
        ["CalendarYear", "CalendarQuarter"]
    )["SalesAmount"].sum()
    /
    sales_dates.groupby(
        ["CalendarYear", "CalendarQuarter"]
    )["SalesOrderNumber"].nunique()
)

aov_by_quarter

CalendarYear  CalendarQuarter
2005          3                  3244.470726
              4                  3208.585436
2006          1                  3210.929127
              2                  3171.672652
              3                  1908.242646
              4                  1765.690588
2007          1                  1793.820177
              2                  1709.443219
              3                   742.717315
              4                   730.809052
2008          1                   759.778283
              2                   844.690670
              3                    52.090809
dtype: float64

In [54]:
aov_table = aov_by_quarter.unstack()
aov_table

CalendarQuarter            1            2            3            4
CalendarYear
2005                     NaN          NaN  3244.470726  3208.585436
2006             3210.929127  3171.672652  1908.242646  1765.690588
2007             1793.820177  1709.443219   742.717315   730.809052
2008              759.778283   844.690670    52.090809          NaN

In [55]:
sales_dates.groupby("ProductKey")["SalesAmount"].sum()

ProductKey
214     78027.70
217     72954.15
222     74353.75
225     19688.10
228     21445.71
         ...
599     30239.44
600     22139.59
604    194396.40
605    196016.37
606    208436.14
Name: SalesAmount, Length: 158, dtype: float64

In [58]:
sales_dates.groupby(
    "MonthNumberOfYear"
)["SalesAmount"].mean().sort_values(ascending=False)

MonthNumberOfYear
12    525.215023
6     523.178287
5     513.629003
3     504.174425
4     497.198440
2     494.640613
7     475.556802
1     473.561228
11    457.687303
8     446.336154
10    442.938555
9     433.830256
Name: SalesAmount, dtype: float64

In [60]:
sales_dates.groupby("MonthNumberOfYear")["SalesAmount"].sum()

MonthNumberOfYear
1     2.375857e+06
2     2.502387e+06
3     2.610615e+06
4     2.778842e+06
5     3.114646e+06
6     3.180924e+06
7     1.911263e+06
8     1.899607e+06
9     1.834668e+06
10    2.009169e+06
11    2.076070e+06
12    3.064630e+06
Name: SalesAmount, dtype: float64

In [61]:
sales_dates.groupby(
    "MonthNumberOfYear"
)["SalesAmount"].sum().sort_values(ascending=False)

MonthNumberOfYear
6     3.180924e+06
5     3.114646e+06
12    3.064630e+06
4     2.778842e+06
3     2.610615e+06
2     2.502387e+06
1     2.375857e+06
11    2.076070e+06
10    2.009169e+06
7     1.911263e+06
8     1.899607e+06
9     1.834668e+06
Name: SalesAmount, dtype: float64

In [65]:
top_products_revenue = (
    sales_dates.groupby("ProductKey")["SalesAmount"].sum()
    .sort_values(ascending=False)
    .reset_index()
)
top_products_revenue

     ProductKey  SalesAmount
0           312   1205876.99
1           310   1202298.72
2           313   1080637.54
3           314   1055589.65
4           311   1005493.87
..          ...          ...
153         530      7425.12
154         480      7307.39
155         484      7218.60
156         481      2679.02
157         482      2427.30

[158 rows x 2 columns]

In [66]:
products.head()

NameError: name 'products' is not defined

In [67]:
products.columns

NameError: name 'products' is not defined

In [69]:
list(globals().keys())

['__name__',
 '__doc__',
 '__package__',
 '__loader__',
 '__spec__',
 '__builtin__',
 '__builtins__',
 '_ih',
 '_oh',
 '_dh',
 'In',
 'Out',
 'get_ipython',
 'exit',
 'quit',
 'open',
 '_',
 '__',
 '___',
 '__vsc_ipynb_file__',
 '_i',
 '_ii',
 '_iii',
 '_i1',
 'sqlite3',
 '_i2',
 'pd',
 'conn',
 'query',
 'tables',
 '_2',
 '_i3',
 'sales',
 '_3',
 '_i4',
 '_4',
 '_i5',
 '_5',
 '_i6',
 '_i7',
 '_7',
 '_i8',
 '_8',
 '_i9',
 '_9',
 '_i10',
 '_i11',
 '_11',
 '_i12',
 '_12',
 '_i13',
 '_13',
 '_i14',
 '_14',
 '_i15',
 '_i16',
 '_16',
 '_i17',
 '_17',
 '_i18',
 '_i19',
 '_19',
 '_i20',
 '_20',
 '_i21',
 '_21',
 '_i22',
 '_22',
 '_i23',
 '_23',
 '_i24',
 '_24',
 '_i25',
 'dates',
 '_25',
 '_i26',
 '_i27',
 'sales_dates',
 '_27',
 '_i28',
 '_28',
 '_i29',
 '_i30',
 'revenue_by_year',
 '_i31',
 '_31',
 '_i32',
 '_32',
 '_i33',
 '_33',
 '_i34',
 '_34',
 '_i35',
 '_35',
 '_i36',
 '_i37',
 'monthly_revenue',
 '_37',
 '_i38',
 '_38',
 '_i39',
 '_i40',
 '_40',
 '_i41',
 'quarterly_revenue',
 '_41',
 '_i42',
 '_42',
 '_i43',
 'quarter_table',
 '_43',
 '_i44',
 '_i45',
 '_i46',
 '_46',
 '_i47',
 '_47',
 '_i48',
 'orders_by_quarter',
 '_48',
 '_i49',
 '_i50',
 '_50',
 '_i51',
 '_51',
 '_i52',
 '_52',
 '_i53',
 'aov_by_quarter',
 '_53',
 '_i54',
 'aov_table',
 '_54',
 '_i55',
 '_55',
 '_i56',
 '_i57',
 '_i58',
 '_58',
 '_i59',
 '_i60',
 '_60',
 '_i61',
 '_61',
 '_i62',
 '_i63',
 '_i64',
 'top_products_revenue',
 '_64',
 '_i65',
 '_65',
 '_i66',
 '_i67',
 '_i68',
 '_i69']

In [70]:
[x for x in globals().keys() if not x.startswith("_")]

['In',
 'Out',
 'get_ipython',
 'exit',
 'quit',
 'open',
 'sqlite3',
 'pd',
 'conn',
 'query',
 'tables',
 'sales',
 'dates',
 'sales_dates',
 'revenue_by_year',
 'monthly_revenue',
 'quarterly_revenue',
 'quarter_table',
 'orders_by_quarter',
 'aov_by_quarter',
 'aov_table',
 'top_products_revenue']

In [71]:
tables

                     name
0              DimProduct
1             DimCustomer
2                 DimDate
3            DimGeography
4      DimProductCategory
5   DimProductSubcategory
6       FactInternetSales
7             FactFinance
8          FactSalesQuota
9       DimSalesTerritory
10            DimScenario
11             DimAccount

In [74]:
products = pd.read_sql("""
SELECT *
FRoM DimProduct
""", conn)
products.head()

,ProductKey,ProductAlternateKey,ProductSubcategoryKey,WeightUnitMeasureCode,SizeUnitMeasureCode,EnglishProductName,SpanishProductName,FrenchProductName,StandardCost,FinishedGoodsFlag,...,ChineseDescription,ArabicDescription,HebrewDescription,ThaiDescription,GermanDescription,JapaneseDescription,TurkishDescription,StartDate,EndDate,Status
0,1,AR-5381,NaN,NaN,NaN,Adjustable Race,NaN,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002-06-01,NaN,Current
1,2,BA-8327,NaN,NaN,NaN,Bearing Ball,NaN,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002-06-01,NaN,Current
2,3,BE-2349,NaN,NaN,NaN,BB Ball Bearing,NaN,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002-06-01,NaN,Current
3,4,BE-2908,NaN,NaN,NaN,Headset Ball Bearings,NaN,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002-06-01,NaN,Current
4,5,BL-2036,NaN,NaN,NaN,Blade,NaN,NaN,NaN,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002-06-01,NaN,Current

In [78]:
top_products_named = top_products_revenue.merge(
    products[["ProductKey", "EnglishProductName"]],
    on="ProductKey",
    how="left"
)
top_products_named.head(10)

   ProductKey  SalesAmount       EnglishProductName
0         312   1205876.99         Road-150 Red, 48
1         310   1202298.72         Road-150 Red, 62
2         313   1080637.54         Road-150 Red, 52
3         314   1055589.65         Road-150 Red, 56
4         311   1005493.87         Road-150 Red, 44
5         361    979960.73   Mountain-200 Black, 42
6         353    979035.78  Mountain-200 Silver, 38
7         363    961600.81   Mountain-200 Black, 46
8         359    954715.84   Mountain-200 Black, 38
9         357    930315.99  Mountain-200 Silver, 46

In [77]:
list(products.columns)

['ProductKey',
 'ProductAlternateKey',
 'ProductSubcategoryKey',
 'WeightUnitMeasureCode',
 'SizeUnitMeasureCode',
 'EnglishProductName',
 'SpanishProductName',
 'FrenchProductName',
 'StandardCost',
 'FinishedGoodsFlag',
 'Color',
 'SafetyStockLevel',
 'ReorderPoint',
 'ListPrice',
 'Size',
 'SizeRange',
 'Weight',
 'DaysToManufacture',
 'ProductLine',
 'DealerPrice',
 'Class',
 'Style',
 'ModelName',
 'LargePhoto',
 'EnglishDescription',
 'FrenchDescription',
 'ChineseDescription',
 'ArabicDescription',
 'HebrewDescription',
 'ThaiDescription',
 'GermanDescription',
 'JapaneseDescription',
 'TurkishDescription',
 'StartDate',
 'EndDate',
 'Status']

In [79]:
top_products_named.head(10)

   ProductKey  SalesAmount       EnglishProductName
0         312   1205876.99         Road-150 Red, 48
1         310   1202298.72         Road-150 Red, 62
2         313   1080637.54         Road-150 Red, 52
3         314   1055589.65         Road-150 Red, 56
4         311   1005493.87         Road-150 Red, 44
5         361    979960.73   Mountain-200 Black, 42
6         353    979035.78  Mountain-200 Silver, 38
7         363    961600.81   Mountain-200 Black, 46
8         359    954715.84   Mountain-200 Black, 38
9         357    930315.99  Mountain-200 Silver, 46

In [80]:
sales_dates.columns

Index(['ProductKey', 'OrderDateKey', 'DueDateKey', 'ShipDateKey',
       'CustomerKey', 'PromotionKey', 'CurrencyKey', 'SalesTerritoryKey',
       'SalesOrderNumber', 'SalesOrderLineNumber', 'RevisionNumber',
       'OrderQuantity', 'UnitPrice', 'ExtendedAmount', 'UnitPriceDiscountPct',
       'DiscountAmount', 'ProductStandardCost', 'TotalProductCost',
       'SalesAmount', 'TaxAmt', 'Freight', 'CarrierTrackingNumber',
       'CustomerPONumber', 'DateKey', 'FullDateAlternateKey',
       'DayNumberOfWeek', 'EnglishDayNameOfWeek', 'SpanishDayNameOfWeek',
       'FrenchDayNameOfWeek', 'DayNumberOfMonth', 'DayNumberOfYear',
       'WeekNumberOfYear', 'EnglishMonthName', 'SpanishMonthName',
       'FrenchMonthName', 'MonthNumberOfYear', 'CalendarQuarter',
       'CalendarYear', 'CalendarSemester', 'FiscalQuarter', 'FiscalYear',
       'FiscalSemester'],
      dtype='str')

In [83]:
sales_dates["Profit"] = (
    sales_dates["SalesAmount"]
    - sales_dates["TotalProductCost"]
)

In [84]:
top_products_profit = (
    sales_dates.groupby("ProductKey")["Profit"].sum()
.sort_values(ascending=False)
)
top_products_profit

ProductKey
312    474150.8446
310    472743.8688
361    445364.7149
353    444944.3510
363    437020.6453
          ...
480      4574.2985
225      4528.2630
484      4518.8436
481      1677.0546
482      1519.4790
Name: Profit, Length: 158, dtype: float64

In [85]:
top_products_profit = (
    sales_dates.groupby("ProductKey")["Profit"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()
)

top_products_profit_named = top_products_profit.merge(
    products[["ProductKey", "EnglishProductName"]],
    on="ProductKey",
    how="left"
)

top_products_profit_named.head(10)

   ProductKey       Profit       EnglishProductName
0         312  474150.8446         Road-150 Red, 48
1         310  472743.8688         Road-150 Red, 62
2         361  445364.7149   Mountain-200 Black, 42
3         353  444944.3510  Mountain-200 Silver, 38
4         363  437020.6453   Mountain-200 Black, 46
5         359  433891.6192   Mountain-200 Black, 38
6         313  424906.6916         Road-150 Red, 52
7         357  422802.5705  Mountain-200 Silver, 46
8         314  415057.8610         Road-150 Red, 56
9         355  413313.2360  Mountain-200 Silver, 42

In [86]:
sales_dates["ProfitMargin"] = (
    sales_dates["Profit"]
    / sales_dates["SalesAmount"]
)

In [87]:
product_margin = (
    sales_dates.groupby("ProductKey")["ProfitMargin"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

product_margin = product_margin.merge(
    products[["ProductKey", "EnglishProductName"]],
    on="ProductKey",
    how="left"
)

product_margin.head(10)

   ProductKey  ProfitMargin          EnglishProductName
0         485      0.626001       Fender Set - Mountain
1         471      0.626000             Classic Vest, S
2         472      0.626000             Classic Vest, M
3         473      0.626000             Classic Vest, L
4         486      0.626000      All-Purpose Bike Stand
5         537      0.626000            HL Mountain Tire
6         483      0.626000         Hitch Rack - 4-Bike
7         484      0.626000       Bike Wash - Dissolver
8         540      0.626000                HL Road Tire
9         476      0.625999  Women's Mountain Shorts, L

In [88]:
product_margin = (
    sales_dates.groupby("ProductKey")["ProfitMargin"]
    .mean()
    .sort_values(ascending=False)
    .reset_index()
)

product_margin = product_margin.merge(
    products[["ProductKey", "EnglishProductName"]],
    on="ProductKey",
    how="left"
)

product_margin.head(10)

   ProductKey  ProfitMargin          EnglishProductName
0         485      0.626001       Fender Set - Mountain
1         471      0.626000             Classic Vest, S
2         472      0.626000             Classic Vest, M
3         473      0.626000             Classic Vest, L
4         486      0.626000      All-Purpose Bike Stand
5         537      0.626000            HL Mountain Tire
6         483      0.626000         Hitch Rack - 4-Bike
7         484      0.626000       Bike Wash - Dissolver
8         540      0.626000                HL Road Tire
9         476      0.625999  Women's Mountain Shorts, L

In [89]:
high_margin_keys = product_margin.head(10)["ProductKey"]

top_margin_products = (
    sales_dates[sales_dates["ProductKey"].isin(high_margin_keys)]
    .groupby("ProductKey")["SalesAmount"]
    .sum()
    .reset_index()
)

top_margin_products = top_margin_products.merge(
    products[["ProductKey", "EnglishProductName"]],
    on="ProductKey",
    how="left"
)

top_margin_products.sort_values(
    "SalesAmount",
    ascending=False
)

   ProductKey  SalesAmount          EnglishProductName
8         537     48860.00            HL Mountain Tire
6         485     46619.58       Fender Set - Mountain
7         486     39591.00      All-Purpose Bike Stand
4         483     39360.00         Hitch Rack - 4-Bike
9         540     27970.80                HL Road Tire
3         476     25406.37  Women's Mountain Shorts, L
1         472     12636.50             Classic Vest, M
2         473     12382.50             Classic Vest, L
0         471     10668.00             Classic Vest, S
5         484      7218.60       Bike Wash - Dissolver

In [90]:
revenue_margin = (
    sales_dates.groupby("ProductKey")
    .agg({
        "SalesAmount": "sum",
        "Profit": "sum",
        "ProfitMargin": "mean"
    })
    .reset_index()
)

revenue_margin = revenue_margin.merge(
    products[["ProductKey", "EnglishProductName"]],
    on="ProductKey",
    how="left"
)

revenue_margin.sort_values(
    "SalesAmount",
    ascending=False
).head(20)

,ProductKey,SalesAmount,Profit,ProfitMargin,EnglishProductName
10,312,1.205877e+06,474150.8446,0.393200,"Road-150 Red, 48"
8,310,1.202299e+06,472743.8688,0.393200,"Road-150 Red, 62"
11,313,1.080638e+06,424906.6916,0.393200,"Road-150 Red, 52"
12,314,1.055590e+06,415057.8610,0.393200,"Road-150 Red, 56"
9,311,1.005494e+06,395360.1998,0.393200,"Road-150 Red, 44"
54,361,9.799607e+05,445364.7149,0.454472,"Mountain-200 Black, 42"
46,353,9.790358e+05,444944.3510,0.454472,"Mountain-200 Silver, 38"
56,363,9.616008e+05,437020.6453,0.454472,"Mountain-200 Black, 46"
52,359,9.547158e+05,433891.6192,0.454472,"Mountain-200 Black, 38"
50,357,9.303160e+05,422802.5705,0.454472,"Mountain-200 Silver, 46"
48,355,9.094361e+05,413313.2360,0.454472,"Mountain-200 Silver, 42"
127,573,4.219804e+05,159677.3817,0.378400,"Touring-1000 Blue, 46"
134,580,4.184435e+05,152146.0800,0.363600,"Road-350-W Yellow, 40"
55,362,4.118687e+05,189600.9282,0.460343,"Mountain-200 Black, 46"
115,561,4.100600e+05,155166.7212,0.378400,"Touring-1000 Yellow, 46"
135,581,3.997327e+05,145342.8000,0.363600,"Road-350-W Yellow, 42"
58,369,3.958227e+05,149779.3032,0.378400,"Road-250 Red, 48"
137,583,3.946297e+05,143487.3600,0.363600,"Road-350-W Yellow, 48"
65,376,3.836060e+05,139479.1297,0.363600,"Road-250 Black, 48"
53,360,3.831814e+05,176394.8934,0.460343,"Mountain-200 Black, 42"

In [91]:
sales_dates[["UnitPriceDiscountPct", "DiscountAmount"]].describe()

       UnitPriceDiscountPct  DiscountAmount
count               60398.0         60398.0
mean                    0.0             0.0
std                     0.0             0.0
min                     0.0             0.0
25%                     0.0             0.0
50%                     0.0             0.0
75%                     0.0             0.0
max                     0.0             0.0

In [97]:
subcategory =pd.read_sql("""
SELECT *
FROM DimProductSubCategory
""", conn)

subcategory.head()

,ProductSubcategoryKey,ProductSubcategoryAlternateKey,EnglishProductSubcategoryName,SpanishProductSubcategoryName,FrenchProductSubcategoryName,ProductCategoryKey
0,1,1,Mountain Bikes,Bicicleta de montaña,VTT,1
1,2,2,Road Bikes,Bicicleta de carretera,Vélo de route,1
2,3,3,Touring Bikes,Bicicleta de paseo,Vélo de randonnée,1
3,4,4,Handlebars,Barra,Barre d'appui,2
4,5,5,Bottom Brackets,Eje de pedalier,Axe de pédalier,2

In [99]:
categories =pd.read_sql("""
SELECT *
FROM DimProductCategory
""", conn)

categories.haed()

AttributeError: 'DataFrame' object has no attribute 'haed'

In [100]:
type(categories)

pandas.DataFrame

In [102]:
dir(categories)

['EnglishProductCategoryName',
 'FrenchProductCategoryName',
 'ProductCategoryAlternateKey',
 'ProductCategoryKey',
 'SpanishProductCategoryName',
 'T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_select_dtypes_indices',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

In [103]:
list(subcategory.columns)

['ProductSubcategoryKey',
 'ProductSubcategoryAlternateKey',
 'EnglishProductSubcategoryName',
 'SpanishProductSubcategoryName',
 'FrenchProductSubcategoryName',
 'ProductCategoryKey']

In [104]:
sales_product_category = sales_dates.merge(
    products[["ProductKey", "ProductSubcategoryKey"]],
    on="ProductKey",
    how="left"
)

sales_product_category = sales_product_category.merge(
    subcategory[[
        "ProductSubcategoryKey",
        "ProductCategoryKey",
        "EnglishProductSubcategoryName"
    ]],
    on="ProductSubcategoryKey",
    how="left"
)

sales_product_category = sales_product_category.merge(
    categories[[
        "ProductCategoryKey",
        "EnglishProductCategoryName"
    ]],
    on="ProductCategoryKey",
    how="left"
)

sales_product_category[[
    "ProductKey",
    "EnglishProductSubcategoryName",
    "EnglishProductCategoryName",
    "SalesAmount",
    "Profit",
    "ProfitMargin"
]].head()

ValueError: You are trying to merge on str and int64 columns for key 'ProductSubcategoryKey'. If you wish to proceed you should use pd.concat

In [105]:
products["ProductSubcategoryKey"] = products["ProductSubcategoryKey"].astype("Int64")
subcategory["ProductSubcategoryKey"] = subcategory["ProductSubcategoryKey"].astype("Int64")
subcategory["ProductCategoryKey"] = subcategory["ProductCategoryKey"].astype("Int64")
categories["ProductCategoryKey"] = categories["ProductCategoryKey"].astype("Int64")

ValueError: invalid literal for int() with base 10: '14.0'

In [106]:
products["ProductSubcategoryKey"] = products["ProductSubcategoryKey"].astype(str)
subcategory["ProductSubcategoryKey"] = subcategory["ProductSubcategoryKey"].astype(str)

subcategory["ProductCategoryKey"] = subcategory["ProductCategoryKey"].astype(str)
categories["ProductCategoryKey"] = categories["ProductCategoryKey"].astype(str)

In [107]:
sales_product_category = sales_dates.merge(
    products[["ProductKey", "ProductSubcategoryKey"]],
    on="ProductKey",
    how="left"
)

sales_product_category = sales_product_category.merge(
    subcategory[[
        "ProductSubcategoryKey",
        "ProductCategoryKey",
        "EnglishProductSubcategoryName"
    ]],
    on="ProductSubcategoryKey",
    how="left"
)

sales_product_category = sales_product_category.merge(
    categories[[
        "ProductCategoryKey",
        "EnglishProductCategoryName"
    ]],
    on="ProductCategoryKey",
    how="left"
)

sales_product_category[[
    "ProductKey",
    "EnglishProductSubcategoryName",
    "EnglishProductCategoryName",
    "SalesAmount",
    "Profit",
    "ProfitMargin"
]].head()

,ProductKey,EnglishProductSubcategoryName,EnglishProductCategoryName,SalesAmount,Profit,ProfitMargin
0,310,NaN,NaN,3578.2700,1406.9758,0.39320
1,346,NaN,NaN,3399.9900,1487.8356,0.43760
2,346,NaN,NaN,3399.9900,1487.8356,0.43760
3,336,NaN,NaN,699.0982,285.9519,0.40903
4,346,NaN,NaN,3399.9900,1487.8356,0.43760

In [109]:
products[["ProductKey", "PrdocutSubcategoryKey"]].head()

KeyError: "['PrdocutSubcategoryKey'] not in index"

In [110]:
list(products.columns)

['ProductKey',
 'ProductAlternateKey',
 'ProductSubcategoryKey',
 'WeightUnitMeasureCode',
 'SizeUnitMeasureCode',
 'EnglishProductName',
 'SpanishProductName',
 'FrenchProductName',
 'StandardCost',
 'FinishedGoodsFlag',
 'Color',
 'SafetyStockLevel',
 'ReorderPoint',
 'ListPrice',
 'Size',
 'SizeRange',
 'Weight',
 'DaysToManufacture',
 'ProductLine',
 'DealerPrice',
 'Class',
 'Style',
 'ModelName',
 'LargePhoto',
 'EnglishDescription',
 'FrenchDescription',
 'ChineseDescription',
 'ArabicDescription',
 'HebrewDescription',
 'ThaiDescription',
 'GermanDescription',
 'JapaneseDescription',
 'TurkishDescription',
 'StartDate',
 'EndDate',
 'Status']

In [111]:
products[["ProductSubcategoryKey"]].head(10)

  ProductSubcategoryKey
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
5                   NaN
6                   NaN
7                   NaN
8                   NaN
9                   NaN

In [112]:
subcategory[["ProductSubcategoryKey"]].head(10)

  ProductSubcategoryKey
0                     1
1                     2
2                     3
3                     4
4                     5
5                     6
6                     7
7                     8
8                     9
9                    10

In [113]:
products["ProductSubcategoryKey"].dtype

In [114]:
subcategory["ProductSubcategoryKey"].dtype

In [115]:
products["ProductSubcategoryKey"].dtype

In [116]:
products[products["ProductKey"].isin(sales_dates["ProductKey"].unique())][
    ["ProductKey", "ProductSubcategoryKey", "EnglishProductName"]
].head(10)

     ProductKey ProductSubcategoryKey           EnglishProductName
213         214                  31.0        Sport-100 Helmet, Red
216         217                  31.0      Sport-100 Helmet, Black
221         222                  31.0       Sport-100 Helmet, Blue
224         225                  19.0                 AWC Logo Cap
227         228                  21.0   Long-Sleeve Logo Jersey, S
230         231                  21.0   Long-Sleeve Logo Jersey, M
233         234                  21.0   Long-Sleeve Logo Jersey, L
236         237                  21.0  Long-Sleeve Logo Jersey, XL
309         310                   2.0             Road-150 Red, 62
310         311                   2.0             Road-150 Red, 44

In [117]:
sold_products = products[products["ProductKey"].isin(sales_dates["ProductKey"].unique())][
    ["ProductKey", "ProductSubcategoryKey", "EnglishProductName"]
]

sales_product_category = sales_dates.merge(
    sold_products,
    on="ProductKey",
    how="left"
)

In [118]:
sales_product_category[["ProductKey", "ProductSubcategoryKey", "EnglishProductName"]].head()

   ProductKey ProductSubcategoryKey       EnglishProductName
0         310                   2.0         Road-150 Red, 62
1         346                   1.0  Mountain-100 Silver, 44
2         346                   1.0  Mountain-100 Silver, 44
3         336                   2.0       Road-650 Black, 62
4         346                   1.0  Mountain-100 Silver, 44

In [119]:
sales_product_category["ProductSubcategoryKey"] = (
    sales_product_category["ProductSubcategoryKey"]
    .astype(float)
    .astype(int)
    .astype(str)
)

subcategory["ProductSubcategoryKey"] = (
    subcategory["ProductSubcategoryKey"]
    .astype(str)
)

In [120]:
sales_product_category = sales_product_category.merge(
    subcategory[[
        "ProductSubcategoryKey",
        "ProductCategoryKey",
        "EnglishProductSubcategoryName"
    ]],
    on="ProductSubcategoryKey",
    how="left"
)

sales_product_category[[
    "ProductKey",
    "EnglishProductName",
    "ProductSubcategoryKey",
    "EnglishProductSubcategoryName",
    "SalesAmount",
    "Profit"
]].head()

,ProductKey,EnglishProductName,ProductSubcategoryKey,EnglishProductSubcategoryName,SalesAmount,Profit
0,310,"Road-150 Red, 62",2,Road Bikes,3578.2700,1406.9758
1,346,"Mountain-100 Silver, 44",1,Mountain Bikes,3399.9900,1487.8356
2,346,"Mountain-100 Silver, 44",1,Mountain Bikes,3399.9900,1487.8356
3,336,"Road-650 Black, 62",2,Road Bikes,699.0982,285.9519
4,346,"Mountain-100 Silver, 44",1,Mountain Bikes,3399.9900,1487.8356

In [121]:
sales_product_category["ProductCategoryKey"] = (
    sales_product_category["ProductCategoryKey"]
    .astype(float)
    .astype(int)
    .astype(str)
)

categories["ProductCategoryKey"] = (
    categories["ProductCategoryKey"]
    .astype(str)
)

sales_product_category = sales_product_category.merge(
    categories[[
        "ProductCategoryKey",
        "EnglishProductCategoryName"
    ]],
    on="ProductCategoryKey",
    how="left"
)

sales_product_category[[
    "ProductKey",
    "EnglishProductName",
    "EnglishProductSubcategoryName",
    "EnglishProductCategoryName",
    "SalesAmount",
    "Profit",
    "ProfitMargin"
]].head()

,ProductKey,EnglishProductName,EnglishProductSubcategoryName,EnglishProductCategoryName,SalesAmount,Profit,ProfitMargin
0,310,"Road-150 Red, 62",Road Bikes,Bikes,3578.2700,1406.9758,0.39320
1,346,"Mountain-100 Silver, 44",Mountain Bikes,Bikes,3399.9900,1487.8356,0.43760
2,346,"Mountain-100 Silver, 44",Mountain Bikes,Bikes,3399.9900,1487.8356,0.43760
3,336,"Road-650 Black, 62",Road Bikes,Bikes,699.0982,285.9519,0.40903
4,346,"Mountain-100 Silver, 44",Mountain Bikes,Bikes,3399.9900,1487.8356,0.43760

In [122]:
category_profitability = (
    sales_product_category
    .groupby("EnglishProductCategoryName")
    .agg({
        "SalesAmount":"sum",
        "Profit":"sum"
    })
    .reset_index()
)

category_profitability["ProfitMargin"] = (
    category_profitability["Profit"]
    / category_profitability["SalesAmount"]
)

category_profitability.sort_values(
    "Profit",
    ascending=False
)

  EnglishProductCategoryName   SalesAmount        Profit  ProfitMargin
1                      Bikes  2.831814e+07  1.150580e+07      0.406305
0                Accessories  7.007600e+05  4.386746e+05      0.625998
2                   Clothing  3.397726e+05  1.364126e+05      0.401482

In [123]:
sales_product_category["EnglishProductCategoryName"]

0              Bikes
1              Bikes
2              Bikes
3              Bikes
4              Bikes
            ...
60393    Accessories
60394       Clothing
60395    Accessories
60396    Accessories
60397       Clothing
Name: EnglishProductCategoryName, Length: 60398, dtype: str

In [127]:
sales_product_category[
    sales_product_category["EnglishProductCategoryName"] =="Components"
    ].head()

Empty DataFrame
Columns: [ProductKey, OrderDateKey, DueDateKey, ShipDateKey, CustomerKey, PromotionKey, CurrencyKey, SalesTerritoryKey, SalesOrderNumber, SalesOrderLineNumber, RevisionNumber, OrderQuantity, UnitPrice, ExtendedAmount, UnitPriceDiscountPct, DiscountAmount, ProductStandardCost, TotalProductCost, SalesAmount, TaxAmt, Freight, CarrierTrackingNumber, CustomerPONumber, DateKey, FullDateAlternateKey, DayNumberOfWeek, EnglishDayNameOfWeek, SpanishDayNameOfWeek, FrenchDayNameOfWeek, DayNumberOfMonth, DayNumberOfYear, WeekNumberOfYear, EnglishMonthName, SpanishMonthName, FrenchMonthName, MonthNumberOfYear, CalendarQuarter, CalendarYear, CalendarSemester, FiscalQuarter, FiscalYear, FiscalSemester, Profit, ProfitMargin, ProductSubcategoryKey, EnglishProductName, ProductCategoryKey, EnglishProductSubcategoryName, EnglishProductCategoryName]
Index: []

[0 rows x 49 columns]

In [128]:
sales_product_category["EnglishProductCategoryName"].value_counts()

EnglishProductCategoryName
Accessories    36092
Bikes          15205
Clothing        9101
Name: count, dtype: int64

In [129]:
subcategory_profitability = (
    sales_product_category
    .groupby("EnglishProductSubcategoryName")
    .agg({
        "SalesAmount": "sum",
        "Profit": "sum"
    })
    .reset_index()
)

subcategory_profitability["ProfitMargin"] = (
    subcategory_profitability["Profit"]
    / subcategory_profitability["SalesAmount"]
)

subcategory_profitability.sort_values(
    "Profit",
    ascending=False
)

   EnglishProductSubcategoryName   SalesAmount        Profit  ProfitMargin
11                    Road Bikes  1.452058e+07  5.537300e+06      0.381341
10                Mountain Bikes  9.952760e+06  4.513624e+06      0.453505
15                 Touring Bikes  3.844801e+06  1.454873e+06      0.378400
14               Tires and Tubes  2.455293e+05  1.537008e+05      0.625998
7                        Helmets  2.253356e+05  1.410598e+05      0.625999
12                        Shorts  7.131981e+04  4.464616e+04      0.625999
9                        Jerseys  1.729507e+05  3.977866e+04      0.230000
2              Bottles and Cages  5.679819e+04  3.555535e+04      0.625994
5                        Fenders  4.661958e+04  2.918390e+04      0.626001
8                Hydration Packs  4.030767e+04  2.523257e+04      0.625999
1                    Bike Stands  3.959100e+04  2.478397e+04      0.626000
0                     Bike Racks  3.936000e+04  2.463936e+04      0.626000
16                         Vests  3.568700e+04  2.234006e+04      0.626000
6                         Gloves  3.502070e+04  2.192290e+04      0.625998
3                           Caps  1.968810e+04  4.528263e+03      0.230000
4                       Cleaners  7.218600e+03  4.518844e+03      0.626000
13                         Socks  5.106320e+03  3.196534e+03      0.625996

In [130]:
top_margin_products = (
    sales_dates
    .groupby("ProductKey")
    .agg({
        "SalesAmount":"sum",
        "Profit":"sum"
    })
    .reset_index()
)

top_margin_products["ProfitMargin"] = (
    top_margin_products["Profit"]
    / top_margin_products["SalesAmount"]
)

top_margin_products = top_margin_products.merge(
    products[["ProductKey","EnglishProductName"]],
    on="ProductKey",
    how="left"
)

top_margin_products.sort_values(
    "ProfitMargin",
    ascending=False
)

,ProductKey,SalesAmount,Profit,ProfitMargin,EnglishProductName
97,485,46619.58,29183.8995,0.626001,Fender Set - Mountain
112,540,27970.80,17509.7208,0.626000,HL Road Tire
83,471,10668.00,6678.1680,0.626000,"Classic Vest, S"
84,472,12636.50,7910.4490,0.626000,"Classic Vest, M"
109,537,48860.00,30586.3600,0.626000,HL Mountain Tire
...,...,...,...,...,...
6,234,22595.48,5196.9604,0.230000,"Long-Sleeve Logo Jersey, L"
5,231,22095.58,5081.9834,0.230000,"Long-Sleeve Logo Jersey, M"
4,228,21445.71,4932.5133,0.230000,"Long-Sleeve Logo Jersey, S"
3,225,19688.10,4528.2630,0.230000,AWC Logo Cap
7,237,20645.87,4748.5501,0.230000,"Long-Sleeve Logo Jersey, XL"

In [131]:
top_margin_products[
    top_margin_products["SalesAmount"] > 50000
].sort_values(
    "ProfitMargin",
    ascending=False
)

,ProductKey,SalesAmount,Profit,ProfitMargin,EnglishProductName
2,222,74353.7500,46545.3625,0.625999,"Sport-100 Helmet, Blue"
0,214,78027.7000,48845.2510,0.625999,"Sport-100 Helmet, Red"
1,217,72954.1500,45669.2145,0.625999,"Sport-100 Helmet, Black"
55,362,411868.7382,189600.9282,0.460343,"Mountain-200 Black, 46"
53,360,383181.3634,176394.8934,0.460343,"Mountain-200 Black, 42"
...,...,...,...,...,...
63,374,346955.7000,126153.0982,0.363600,"Road-250 Black, 44"
69,380,307862.1000,111938.6646,0.363600,"Road-250 Black, 58"
61,372,327408.9000,119045.8814,0.363600,"Road-250 Red, 58"
67,378,359172.4500,130595.1087,0.363600,"Road-250 Black, 52"
65,376,383605.9500,139479.1297,0.363600,"Road-250 Black, 48"

In [132]:
sales_product_category.columns.tolist()

['ProductKey',
 'OrderDateKey',
 'DueDateKey',
 'ShipDateKey',
 'CustomerKey',
 'PromotionKey',
 'CurrencyKey',
 'SalesTerritoryKey',
 'SalesOrderNumber',
 'SalesOrderLineNumber',
 'RevisionNumber',
 'OrderQuantity',
 'UnitPrice',
 'ExtendedAmount',
 'UnitPriceDiscountPct',
 'DiscountAmount',
 'ProductStandardCost',
 'TotalProductCost',
 'SalesAmount',
 'TaxAmt',
 'Freight',
 'CarrierTrackingNumber',
 'CustomerPONumber',
 'DateKey',
 'FullDateAlternateKey',
 'DayNumberOfWeek',
 'EnglishDayNameOfWeek',
 'SpanishDayNameOfWeek',
 'FrenchDayNameOfWeek',
 'DayNumberOfMonth',
 'DayNumberOfYear',
 'WeekNumberOfYear',
 'EnglishMonthName',
 'SpanishMonthName',
 'FrenchMonthName',
 'MonthNumberOfYear',
 'CalendarQuarter',
 'CalendarYear',
 'CalendarSemester',
 'FiscalQuarter',
 'FiscalYear',
 'FiscalSemester',
 'Profit',
 'ProfitMargin',
 'ProductSubcategoryKey',
 'EnglishProductName',
 'ProductCategoryKey',
 'EnglishProductSubcategoryName',
 'EnglishProductCategoryName']

In [133]:
sales_product_category["FullDateAlternateKey"] = pd.to_datetime(
    sales_product_category["FullDateAlternateKey"]
)

sales_product_category["Year"] = (
    sales_product_category["FullDateAlternateKey"].dt.year
)

In [134]:
product_yearly_sales = (
    sales_product_category
    .groupby(["EnglishProductName", "Year"])
    .agg({"SalesAmount":"sum"})
    .reset_index()
)

product_yearly_sales.head()

       EnglishProductName  Year  SalesAmount
0            AWC Logo Cap  2007      7956.15
1            AWC Logo Cap  2008     11731.95
2  All-Purpose Bike Stand  2007     18921.00
3  All-Purpose Bike Stand  2008     20670.00
4   Bike Wash - Dissolver  2007      3044.85

In [135]:
sales_product_category["EnglishProductName"].nunique()

130

In [136]:
sales_product_category["FullDateAlternateKey"] = pd.to_datetime(
    sales_product_category["FullDateAlternateKey"]
)

sales_product_category["Year"] = (
    sales_product_category["FullDateAlternateKey"].dt.year
)

In [137]:
product_yearly_sales = (
    sales_product_category
    .groupby(["EnglishProductName", "Year"])
    .agg({"SalesAmount":"sum"})
    .reset_index()
)

product_yearly_sales.head()

       EnglishProductName  Year  SalesAmount
0            AWC Logo Cap  2007      7956.15
1            AWC Logo Cap  2008     11731.95
2  All-Purpose Bike Stand  2007     18921.00
3  All-Purpose Bike Stand  2008     20670.00
4   Bike Wash - Dissolver  2007      3044.85

In [138]:
sales_product_category["Year"].value_counts().sort_index()

Year
2005     1013
2006     2677
2007    24443
2008    32265
Name: count, dtype: int64

In [139]:
product_revenue = (
    sales_product_category
    .groupby("EnglishProductName")
    .agg({"SalesAmount":"sum"})
    .reset_index()
    .sort_values("SalesAmount", ascending=False)
)

product_revenue.head(20)

          EnglishProductName   SalesAmount
34    Mountain-200 Black, 46  1.373470e+06
33    Mountain-200 Black, 42  1.363142e+06
35   Mountain-200 Silver, 38  1.339463e+06
37   Mountain-200 Silver, 46  1.301100e+06
32    Mountain-200 Black, 38  1.294866e+06
36   Mountain-200 Silver, 42  1.257435e+06
58          Road-150 Red, 48  1.205877e+06
61          Road-150 Red, 62  1.202299e+06
59          Road-150 Red, 52  1.080638e+06
60          Road-150 Red, 56  1.055590e+06
57          Road-150 Red, 44  1.005494e+06
64        Road-250 Black, 52  7.344012e+05
69          Road-250 Red, 58  7.026377e+05
63        Road-250 Black, 48  6.912063e+05
62        Road-250 Black, 44  6.283773e+05
65        Road-250 Black, 58  6.220071e+05
104    Touring-1000 Blue, 46  4.219804e+05
70     Road-350-W Yellow, 40  4.184435e+05
108  Touring-1000 Yellow, 46  4.100600e+05
71     Road-350-W Yellow, 42  3.997327e+05

In [140]:
sales_product_category["Quarter"] = (
    sales_product_category["FullDateAlternateKey"]
    .dt.to_period("Q")
)

In [141]:
top_products = product_revenue.head(20)["EnglishProductName"]

In [143]:
top_product_quarters = (
    sales_product_category[
        sales_product_category["EnglishProductName"].isin(top_products)
        ]
        .groupby(["EnglishProductName", "Quarter"])
        .agg[{"SalesAmount":"sum"}]
        .reset_index()
)
top_product_quarters.head()

TypeError: 'method' object is not subscriptable

In [144]:
sales_product_category[["FullDateAlternateKey", "Quarter"]].head()

  FullDateAlternateKey Quarter
0           2005-07-01  2005Q3
1           2005-07-01  2005Q3
2           2005-07-01  2005Q3
3           2005-07-01  2005Q3
4           2005-07-01  2005Q3

In [145]:
sales_product_category[["FullDateAlternateKey", "Quarter"]].head()

  FullDateAlternateKey Quarter
0           2005-07-01  2005Q3
1           2005-07-01  2005Q3
2           2005-07-01  2005Q3
3           2005-07-01  2005Q3
4           2005-07-01  2005Q3

In [146]:
type(top_products)

pandas.Series

In [147]:
top-products.head()

NameError: name 'top' is not defined

In [148]:
top_products.head()

34     Mountain-200 Black, 46
33     Mountain-200 Black, 42
35    Mountain-200 Silver, 38
37    Mountain-200 Silver, 46
32     Mountain-200 Black, 38
Name: EnglishProductName, dtype: str

In [149]:
top_product_quarters = (
    sales_product_category[
        sales_product_category["EnglishProductName"].isin(top_products)
    ]
    .groupby(["EnglishProductName", "Quarter"])
    .agg({"SalesAmount":"sum"})
    .reset_index()
)

top_product_quarters.head()

       EnglishProductName Quarter  SalesAmount
0  Mountain-200 Black, 38  2006Q3   36883.7676
1  Mountain-200 Black, 38  2006Q4   69669.3388
2  Mountain-200 Black, 38  2007Q1   98356.7136
3  Mountain-200 Black, 38  2007Q2  135240.4812
4  Mountain-200 Black, 38  2007Q3  158354.3100

In [150]:
top_product_quarter_table = top_product_quarters.pivot(
    index="EnglishProductName",
    columns="Quarter",
    values="SalesAmount"
).fillna(0)

top_product_quarter_table

Quarter,2005Q3,2005Q4,2006Q1,2006Q2,2006Q3,2006Q4,2007Q1,2007Q2,2007Q3,2007Q4,2008Q1,2008Q2
EnglishProductName,,,,,,,,,,,,
"Mountain-200 Black, 38",0.00,0.00,0.00,0.00,36883.7676,69669.3388,98356.7136,135240.4812,158354.31,208844.09,268513.83,319003.61
"Mountain-200 Black, 42",0.00,0.00,0.00,0.00,63522.0442,96307.6154,94258.5172,129093.1866,156059.32,247858.92,245563.93,330478.56
"Mountain-200 Black, 46",0.00,0.00,0.00,0.00,73767.5352,90160.3208,131142.2848,116798.5974,197369.14,234088.98,236383.97,293758.72
"Mountain-200 Silver, 38",0.00,0.00,0.00,0.00,51785.4900,84928.2036,109785.2388,113928.0780,183279.21,206479.11,229679.01,359598.45
"Mountain-200 Silver, 42",0.00,0.00,0.00,0.00,57999.7488,78713.9448,80785.3644,130499.4348,167039.28,206479.11,227359.02,308558.67
"Mountain-200 Silver, 46",0.00,0.00,0.00,0.00,45571.2312,57999.7488,111856.6584,155356.4700,120639.48,229679.01,273758.82,306238.68
"Road-150 Red, 44",218274.47,282683.33,236165.82,268370.25,0.0000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0.00
"Road-150 Red, 48",268370.25,279105.06,325622.57,332779.11,0.0000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0.00
"Road-150 Red, 52",207539.66,264791.98,286261.60,322044.30,0.0000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0.00
"Road-150 Red, 56",193226.58,293418.14,279105.06,289839.87,0.0000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0.00
"Road-150 Red, 62",279105.06,314887.76,304152.95,304152.95,0.0000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0.00
"Road-250 Black, 44",0.00,0.00,0.00,0.00,89444.0625,54539.0625,69810.0000,67628.4375,134384.25,75743.85,75743.85,61083.75
"Road-250 Black, 48",0.00,0.00,0.00,0.00,119985.9375,65446.8750,85080.9375,37086.5625,119724.15,107507.40,78187.20,78187.20
"Road-250 Black, 52",0.00,0.00,0.00,0.00,113441.2500,122167.5000,65446.8750,74173.1250,107507.40,109950.75,75743.85,65970.45
"Road-250 Black, 58",0.00,0.00,0.00,0.00,100351.8750,71991.5625,54539.0625,87262.5000,75743.85,85517.25,73300.50,73300.50
"Road-250 Red, 58",0.00,0.00,0.00,0.00,130893.7500,104715.0000,52357.5000,87262.5000,87960.60,85517.25,90403.95,63527.10
"Road-350-W Yellow, 40",0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.0000,57833.66,93554.45,113966.33,153089.10
"Road-350-W Yellow, 42",0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.0000,40823.76,96956.43,112265.34,149687.12
"Touring-1000 Blue, 46",0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.0000,38145.12,100130.94,135891.99,147812.34
"Touring-1000 Yellow, 46",0.00,0.00,0.00,0.00,0.0000,0.0000,0.0000,0.0000,45297.33,92978.73,112051.29,159732.69

In [151]:
top_product_quarter_table["FirstQuarterSales"] = top_product_quarter_table.iloc[:, 0]
top_product_quarter_table["LastQuarterSales"] = top_product_quarter_table.iloc[:, -1]

top_product_quarter_table["RevenueChange"] = (
    top_product_quarter_table["LastQuarterSales"]
    - top_product_quarter_table["FirstQuarterSales"]
)

top_product_quarter_table["RevenueChangePct"] = (
    top_product_quarter_table["RevenueChange"]
    / top_product_quarter_table["FirstQuarterSales"]
) * 100

top_product_quarter_table.sort_values("RevenueChangePct").head(10)

Quarter,2005Q3,2005Q4,2006Q1,2006Q2,2006Q3,2006Q4,2007Q1,2007Q2,2007Q3,2007Q4,2008Q1,2008Q2,FirstQuarterSales,LastQuarterSales,RevenueChange,RevenueChangePct
EnglishProductName,,,,,,,,,,,,,,,,
"Road-150 Red, 44",218274.47,282683.33,236165.82,268370.25,0.0000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0.00,218274.47,218274.47,0.0,0.0
"Road-150 Red, 48",268370.25,279105.06,325622.57,332779.11,0.0000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0.00,268370.25,268370.25,0.0,0.0
"Road-150 Red, 52",207539.66,264791.98,286261.60,322044.30,0.0000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0.00,207539.66,207539.66,0.0,0.0
"Road-150 Red, 56",193226.58,293418.14,279105.06,289839.87,0.0000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0.00,193226.58,193226.58,0.0,0.0
"Road-150 Red, 62",279105.06,314887.76,304152.95,304152.95,0.0000,0.0000,0.0000,0.0000,0.00,0.00,0.00,0.00,279105.06,279105.06,0.0,0.0
"Mountain-200 Black, 38",0.00,0.00,0.00,0.00,36883.7676,69669.3388,98356.7136,135240.4812,158354.31,208844.09,268513.83,319003.61,0.00,0.00,0.0,NaN
"Mountain-200 Black, 42",0.00,0.00,0.00,0.00,63522.0442,96307.6154,94258.5172,129093.1866,156059.32,247858.92,245563.93,330478.56,0.00,0.00,0.0,NaN
"Mountain-200 Black, 46",0.00,0.00,0.00,0.00,73767.5352,90160.3208,131142.2848,116798.5974,197369.14,234088.98,236383.97,293758.72,0.00,0.00,0.0,NaN
"Mountain-200 Silver, 38",0.00,0.00,0.00,0.00,51785.4900,84928.2036,109785.2388,113928.0780,183279.21,206479.11,229679.01,359598.45,0.00,0.00,0.0,NaN
"Mountain-200 Silver, 42",0.00,0.00,0.00,0.00,57999.7488,78713.9448,80785.3644,130499.4348,167039.28,206479.11,227359.02,308558.67,0.00,0.00,0.0,NaN

In [154]:
for name in globals().keys():
    print(name)

__name__

RuntimeError: dictionary changed size during iteration

In [158]:
for name, obj in globals().items():
    if isinstance(obj, pd.DataFrame):
        print(name)

RuntimeError: dictionary changed size during iteration

In [159]:
all_vars = list(globals().items())

for name, obj in all_vars:
    if isinstance(obj, pd.DataFrame):
        print(name)

___
tables
_2
sales
_3
_8
dates
_25
sales_dates
_27
_35
quarter_table
_43
orders_by_quarter
_50
aov_table
_54
top_products_revenue
_65
_71
products
_74
top_products_named
_78
_79
top_products_profit
top_products_profit_named
_85
product_margin
_87
_88
top_margin_products
_89
revenue_margin
_90
_91
subcategory
_92
category
_97
categories
sales_product_category
_107
_111
_112
_116
sold_products
_118
_120
_121
category_profitability
_122
_127
subcategory_profitability
_129
_130
_131
product_yearly_sales
_134
_137
product_revenue
_139
_144
_145
top_product_quarters
_149
top_product_quarter_table
_150
_151

In [160]:
for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        print(name)

___
tables
_2
sales
_3
_8
dates
_25
sales_dates
_27
_35
quarter_table
_43
orders_by_quarter
_50
aov_table
_54
top_products_revenue
_65
_71
products
_74
top_products_named
_78
_79
top_products_profit
top_products_profit_named
_85
product_margin
_87
_88
top_margin_products
_89
revenue_margin
_90
_91
subcategory
_92
category
_97
categories
sales_product_category
_107
_111
_112
_116
sold_products
_118
_120
_121
category_profitability
_122
_127
subcategory_profitability
_129
_130
_131
product_yearly_sales
_134
_137
product_revenue
_139
_144
_145
top_product_quarters
_149
top_product_quarter_table
_150
_151

In [161]:
df_names = []

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        df_names.append(name)

print(df_names)

['___', 'tables', '_2', 'sales', '_3', '_8', 'dates', '_25', 'sales_dates', '_27', '_35', 'quarter_table', '_43', 'orders_by_quarter', '_50', 'aov_table', '_54', 'top_products_revenue', '_65', '_71', 'products', '_74', 'top_products_named', '_78', '_79', 'top_products_profit', 'top_products_profit_named', '_85', 'product_margin', '_87', '_88', 'top_margin_products', '_89', 'revenue_margin', '_90', '_91', 'subcategory', '_92', 'category', '_97', 'categories', 'sales_product_category', '_107', '_111', '_112', '_116', 'sold_products', '_118', '_120', '_121', 'category_profitability', '_122', '_127', 'subcategory_profitability', '_129', '_130', '_131', 'product_yearly_sales', '_134', '_137', 'product_revenue', '_139', '_144', '_145', 'top_product_quarters', '_149', 'top_product_quarter_table', '_150', '_151']

In [162]:
sales_dates.columns.tolist()

['ProductKey',
 'OrderDateKey',
 'DueDateKey',
 'ShipDateKey',
 'CustomerKey',
 'PromotionKey',
 'CurrencyKey',
 'SalesTerritoryKey',
 'SalesOrderNumber',
 'SalesOrderLineNumber',
 'RevisionNumber',
 'OrderQuantity',
 'UnitPrice',
 'ExtendedAmount',
 'UnitPriceDiscountPct',
 'DiscountAmount',
 'ProductStandardCost',
 'TotalProductCost',
 'SalesAmount',
 'TaxAmt',
 'Freight',
 'CarrierTrackingNumber',
 'CustomerPONumber',
 'DateKey',
 'FullDateAlternateKey',
 'DayNumberOfWeek',
 'EnglishDayNameOfWeek',
 'SpanishDayNameOfWeek',
 'FrenchDayNameOfWeek',
 'DayNumberOfMonth',
 'DayNumberOfYear',
 'WeekNumberOfYear',
 'EnglishMonthName',
 'SpanishMonthName',
 'FrenchMonthName',
 'MonthNumberOfYear',
 'CalendarQuarter',
 'CalendarYear',
 'CalendarSemester',
 'FiscalQuarter',
 'FiscalYear',
 'FiscalSemester',
 'Profit',
 'ProfitMargin']

In [164]:
[col for col in sales_dates.columns if "Territory" in col]

['SalesTerritoryKey']

In [165]:
territories =pd.read_sql("""
SELECT *
FROM DimSalesTerritory
""", conn)
territories.head()

,SalesTerritoryKey,SalesTerritoryAlternateKey,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup
0,1,1,Northwest,United States,North America
1,2,2,Northeast,United States,North America
2,3,3,Central,United States,North America
3,4,4,Southwest,United States,North America
4,5,5,Southeast,United States,North America

In [166]:
sales_region = sales_dates.merge(
    territories,
    on="SalesTerritoryKey",
    how="left"
)
sales_region.head()

,ProductKey,OrderDateKey,DueDateKey,ShipDateKey,CustomerKey,PromotionKey,CurrencyKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,...,CalendarSemester,FiscalQuarter,FiscalYear,FiscalSemester,Profit,ProfitMargin,SalesTerritoryAlternateKey,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup
0,310,20050701,20050713,20050708,21768,1,19,6,SO43697,1,...,2,1,2006,1,1406.9758,0.39320,6,Canada,Canada,North America
1,346,20050701,20050713,20050708,28389,1,39,7,SO43698,1,...,2,1,2006,1,1487.8356,0.43760,7,France,France,Europe
2,346,20050701,20050713,20050708,25863,1,100,1,SO43699,1,...,2,1,2006,1,1487.8356,0.43760,1,Northwest,United States,North America
3,336,20050701,20050713,20050708,14501,1,100,4,SO43700,1,...,2,1,2006,1,285.9519,0.40903,4,Southwest,United States,North America
4,346,20050701,20050713,20050708,11003,1,6,9,SO43701,1,...,2,1,2006,1,1487.8356,0.43760,9,Australia,Australia,Pacific

In [167]:
sales_region.columns.tolist()

['ProductKey',
 'OrderDateKey',
 'DueDateKey',
 'ShipDateKey',
 'CustomerKey',
 'PromotionKey',
 'CurrencyKey',
 'SalesTerritoryKey',
 'SalesOrderNumber',
 'SalesOrderLineNumber',
 'RevisionNumber',
 'OrderQuantity',
 'UnitPrice',
 'ExtendedAmount',
 'UnitPriceDiscountPct',
 'DiscountAmount',
 'ProductStandardCost',
 'TotalProductCost',
 'SalesAmount',
 'TaxAmt',
 'Freight',
 'CarrierTrackingNumber',
 'CustomerPONumber',
 'DateKey',
 'FullDateAlternateKey',
 'DayNumberOfWeek',
 'EnglishDayNameOfWeek',
 'SpanishDayNameOfWeek',
 'FrenchDayNameOfWeek',
 'DayNumberOfMonth',
 'DayNumberOfYear',
 'WeekNumberOfYear',
 'EnglishMonthName',
 'SpanishMonthName',
 'FrenchMonthName',
 'MonthNumberOfYear',
 'CalendarQuarter',
 'CalendarYear',
 'CalendarSemester',
 'FiscalQuarter',
 'FiscalYear',
 'FiscalSemester',
 'Profit',
 'ProfitMargin',
 'SalesTerritoryAlternateKey',
 'SalesTerritoryRegion',
 'SalesTerritoryCountry',
 'SalesTerritoryGroup']

In [173]:
region_performance = (
    sales_region
    .groupby("SalesTerritoryRegion")
    .agg({
        "SalesAmount":"sum",
        "Profit":"sum"
    })
    .reset_index()
    .sort_values("SalesAmount", ascending=False)
)
region_performance

  SalesTerritoryRegion   SalesAmount        Profit
0            Australia  9.061001e+06  3.685855e+06
8            Southwest  5.718151e+06  2.371763e+06
6            Northwest  3.649867e+06  1.519631e+06
9       United Kingdom  3.391712e+06  1.390491e+06
4              Germany  2.894312e+06  1.187371e+06
3               France  2.644018e+06  1.086265e+06
1               Canada  1.977845e+06  8.299215e+05
7            Southeast  1.223885e+04  5.332426e+03
5            Northeast  6.532468e+03  2.902762e+03
2              Central  3.000830e+03  1.350920e+03

In [176]:
region_cost_performance = (
    sales_region
    .groupby("SalesTerritoryRegion")
    .agg({"SalesAmount":"sum",
          "TotalProductCost":"sum",
          "Profit":"sum"
          })
          .reset_index()
)
region_cost_performance["ProfitMarginPct"] = (
    region_cost_performance["Profit"]
    / region_cost_performance["SalesAmount"]
)*100

region_cost_performance.sort_values(
    "ProfitMarginPct",
    ascending=True
)

,SalesTerritoryRegion,SalesAmount,TotalProductCost,Profit,ProfitMarginPct
0,Australia,9.061001e+06,5.375146e+06,3.685855e+06,40.678235
9,United Kingdom,3.391712e+06,2.001221e+06,1.390491e+06,40.996721
4,Germany,2.894312e+06,1.706942e+06,1.187371e+06,41.024279
3,France,2.644018e+06,1.557753e+06,1.086265e+06,41.083867
8,Southwest,5.718151e+06,3.346387e+06,2.371763e+06,41.477804
6,Northwest,3.649867e+06,2.130235e+06,1.519631e+06,41.635256
1,Canada,1.977845e+06,1.147923e+06,8.299215e+05,41.960900
7,Southeast,1.223885e+04,6.906423e+03,5.332426e+03,43.569669
5,Northeast,6.532468e+03,3.629706e+03,2.902762e+03,44.435919
2,Central,3.000830e+03,1.649909e+03,1.350920e+03,45.018231

In [177]:
[col for col in sales_region.columns if "Customer" in col or "Order" in col]

['OrderDateKey',
 'CustomerKey',
 'SalesOrderNumber',
 'SalesOrderLineNumber',
 'OrderQuantity',
 'CustomerPONumber']

In [178]:

region_customer_order = (
    sales_region
    .groupby("SalesTerritoryRegion")
    .agg({
        "SalesAmount": "sum",
        "Profit": "sum",
        "CustomerKey": "nunique",
        "SalesOrderNumber": "nunique"
    })
    .reset_index()
)

region_customer_order["RevenuePerCustomer"] = (
    region_customer_order["SalesAmount"]
    / region_customer_order["CustomerKey"]
)

region_customer_order["ProfitPerOrder"] = (
    region_customer_order["Profit"]
    / region_customer_order["SalesOrderNumber"]
)

region_customer_order.sort_values(
    "RevenuePerCustomer",
    ascending=False
)

,SalesTerritoryRegion,SalesAmount,Profit,CustomerKey,SalesOrderNumber,RevenuePerCustomer,ProfitPerOrder
0,Australia,9.061001e+06,3.685855e+06,3591,6718,2523.252739,548.653629
9,United Kingdom,3.391712e+06,1.390491e+06,1913,3031,1772.980769,458.756443
4,Germany,2.894312e+06,1.187371e+06,1780,2484,1626.018168,478.007554
3,France,2.644018e+06,1.086265e+06,1810,2484,1460.783268,437.304638
8,Southwest,5.718151e+06,2.371763e+06,4450,5473,1284.977711,433.357098
1,Canada,1.977845e+06,8.299215e+05,1571,3375,1258.971905,245.902667
6,Northwest,3.649867e+06,1.519631e+06,3341,4058,1092.447336,374.477895
7,Southeast,1.223885e+04,5.332426e+03,12,17,1019.904133,313.672129
5,Northeast,6.532468e+03,2.902762e+03,8,10,816.558525,290.276230
2,Central,3.000830e+03,1.350920e+03,8,9,375.103700,150.102267

In [ ]:
region_category_performance = (
    sales_product_category
    .groupby(["SalesTerritoryRegion", "EnglishProductCategoryName"])
    .agg({
        "SalesAmount":"sum",
        "Profit":"sum"
    })
    .reset_index()
    .sort_values("SalesAmount", ascending=False)
)
region_category_performance.head(20)

KeyError: 'SalesTerritoryRegion'

In [180]:
sales_product_category.columns.tolist()

['ProductKey',
 'OrderDateKey',
 'DueDateKey',
 'ShipDateKey',
 'CustomerKey',
 'PromotionKey',
 'CurrencyKey',
 'SalesTerritoryKey',
 'SalesOrderNumber',
 'SalesOrderLineNumber',
 'RevisionNumber',
 'OrderQuantity',
 'UnitPrice',
 'ExtendedAmount',
 'UnitPriceDiscountPct',
 'DiscountAmount',
 'ProductStandardCost',
 'TotalProductCost',
 'SalesAmount',
 'TaxAmt',
 'Freight',
 'CarrierTrackingNumber',
 'CustomerPONumber',
 'DateKey',
 'FullDateAlternateKey',
 'DayNumberOfWeek',
 'EnglishDayNameOfWeek',
 'SpanishDayNameOfWeek',
 'FrenchDayNameOfWeek',
 'DayNumberOfMonth',
 'DayNumberOfYear',
 'WeekNumberOfYear',
 'EnglishMonthName',
 'SpanishMonthName',
 'FrenchMonthName',
 'MonthNumberOfYear',
 'CalendarQuarter',
 'CalendarYear',
 'CalendarSemester',
 'FiscalQuarter',
 'FiscalYear',
 'FiscalSemester',
 'Profit',
 'ProfitMargin',
 'ProductSubcategoryKey',
 'EnglishProductName',
 'ProductCategoryKey',
 'EnglishProductSubcategoryName',
 'EnglishProductCategoryName',
 'Year',
 'Quarter']

In [181]:
sales_product_region = sales_product_category.merge(
    territories[
        [
            "SalesTerritoryKey",
            "SalesTerritoryRegion",
            "SalesTerritoryCountry",
            "SalesTerritoryGroup"
        ]
    ],
    on="SalesTerritoryKey",
    how="left"
)

sales_product_region.head()

,ProductKey,OrderDateKey,DueDateKey,ShipDateKey,CustomerKey,PromotionKey,CurrencyKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,...,ProductSubcategoryKey,EnglishProductName,ProductCategoryKey,EnglishProductSubcategoryName,EnglishProductCategoryName,Year,Quarter,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup
0,310,20050701,20050713,20050708,21768,1,19,6,SO43697,1,...,2,"Road-150 Red, 62",1,Road Bikes,Bikes,2005,2005Q3,Canada,Canada,North America
1,346,20050701,20050713,20050708,28389,1,39,7,SO43698,1,...,1,"Mountain-100 Silver, 44",1,Mountain Bikes,Bikes,2005,2005Q3,France,France,Europe
2,346,20050701,20050713,20050708,25863,1,100,1,SO43699,1,...,1,"Mountain-100 Silver, 44",1,Mountain Bikes,Bikes,2005,2005Q3,Northwest,United States,North America
3,336,20050701,20050713,20050708,14501,1,100,4,SO43700,1,...,2,"Road-650 Black, 62",1,Road Bikes,Bikes,2005,2005Q3,Southwest,United States,North America
4,346,20050701,20050713,20050708,11003,1,6,9,SO43701,1,...,1,"Mountain-100 Silver, 44",1,Mountain Bikes,Bikes,2005,2005Q3,Australia,Australia,Pacific

In [182]:
region_category_performance = (
    sales_product_region
    .groupby(["SalesTerritoryRegion", "EnglishProductCategoryName"])
    .agg({
        "SalesAmount": "sum",
        "Profit": "sum"
    })
    .reset_index()
    .sort_values("SalesAmount", ascending=False)
)

region_category_performance.head(20)

   SalesTerritoryRegion EnglishProductCategoryName   SalesAmount        Profit
1             Australia                      Bikes  8.852050e+06  3.572267e+06
25            Southwest                      Bikes  5.498312e+06  2.248877e+06
19            Northwest                      Bikes  3.481485e+06  1.425967e+06
28       United Kingdom                      Bikes  3.282843e+06  1.331206e+06
13              Germany                      Bikes  2.808514e+06  1.140642e+06
10               France                      Bikes  2.553576e+06  1.036736e+06
4                Canada                      Bikes  1.821302e+06  7.414512e+05
24            Southwest                Accessories  1.451254e+05  9.084829e+04
0             Australia                Accessories  1.386906e+05  8.682010e+04
18            Northwest                Accessories  1.101508e+05  6.895423e+04
3                Canada                Accessories  1.033779e+05  6.471437e+04
27       United Kingdom                Accessories  7.663004e+04  4.797026e+04
26            Southwest                   Clothing  7.471361e+04  3.203811e+04
2             Australia                   Clothing  7.025995e+04  2.676768e+04
9                France                Accessories  6.340678e+04  3.969253e+04
12              Germany                Accessories  6.223259e+04  3.895749e+04
20            Northwest                   Clothing  5.823043e+04  2.470965e+04
5                Canada                   Clothing  5.316462e+04  2.375591e+04
29       United Kingdom                   Clothing  3.223951e+04  1.131432e+04
11               France                   Clothing  2.703522e+04  9.836599e+03

In [183]:
region_category_table = region_category_performance.pivot(
    index="SalesTerritoryRegion",
    columns="EnglishProductCategoryName",
    values="SalesAmount"
).fillna(0)

region_category_table

EnglishProductCategoryName  Accessories         Bikes  Clothing
SalesTerritoryRegion
Australia                     138690.63  8.852050e+06  70259.95
Canada                        103377.85  1.821302e+06  53164.62
Central                          232.46  2.611410e+03    156.96
France                         63406.78  2.553576e+06  27035.22
Germany                        62232.59  2.808514e+06  23565.40
Northeast                        381.42  6.045078e+03    105.97
Northwest                     110150.80  3.481485e+06  58230.43
Southeast                        531.97  1.140594e+04    300.94
Southwest                     145125.42  5.498312e+06  74713.61
United Kingdom                 76630.04  3.282843e+06  32239.51

In [184]:
sales_region.columns.tolist()

['ProductKey',
 'OrderDateKey',
 'DueDateKey',
 'ShipDateKey',
 'CustomerKey',
 'PromotionKey',
 'CurrencyKey',
 'SalesTerritoryKey',
 'SalesOrderNumber',
 'SalesOrderLineNumber',
 'RevisionNumber',
 'OrderQuantity',
 'UnitPrice',
 'ExtendedAmount',
 'UnitPriceDiscountPct',
 'DiscountAmount',
 'ProductStandardCost',
 'TotalProductCost',
 'SalesAmount',
 'TaxAmt',
 'Freight',
 'CarrierTrackingNumber',
 'CustomerPONumber',
 'DateKey',
 'FullDateAlternateKey',
 'DayNumberOfWeek',
 'EnglishDayNameOfWeek',
 'SpanishDayNameOfWeek',
 'FrenchDayNameOfWeek',
 'DayNumberOfMonth',
 'DayNumberOfYear',
 'WeekNumberOfYear',
 'EnglishMonthName',
 'SpanishMonthName',
 'FrenchMonthName',
 'MonthNumberOfYear',
 'CalendarQuarter',
 'CalendarYear',
 'CalendarSemester',
 'FiscalQuarter',
 'FiscalYear',
 'FiscalSemester',
 'Profit',
 'ProfitMargin',
 'SalesTerritoryAlternateKey',
 'SalesTerritoryRegion',
 'SalesTerritoryCountry',
 'SalesTerritoryGroup']

In [185]:
sales_dates.columns.tolist()

['ProductKey',
 'OrderDateKey',
 'DueDateKey',
 'ShipDateKey',
 'CustomerKey',
 'PromotionKey',
 'CurrencyKey',
 'SalesTerritoryKey',
 'SalesOrderNumber',
 'SalesOrderLineNumber',
 'RevisionNumber',
 'OrderQuantity',
 'UnitPrice',
 'ExtendedAmount',
 'UnitPriceDiscountPct',
 'DiscountAmount',
 'ProductStandardCost',
 'TotalProductCost',
 'SalesAmount',
 'TaxAmt',
 'Freight',
 'CarrierTrackingNumber',
 'CustomerPONumber',
 'DateKey',
 'FullDateAlternateKey',
 'DayNumberOfWeek',
 'EnglishDayNameOfWeek',
 'SpanishDayNameOfWeek',
 'FrenchDayNameOfWeek',
 'DayNumberOfMonth',
 'DayNumberOfYear',
 'WeekNumberOfYear',
 'EnglishMonthName',
 'SpanishMonthName',
 'FrenchMonthName',
 'MonthNumberOfYear',
 'CalendarQuarter',
 'CalendarYear',
 'CalendarSemester',
 'FiscalQuarter',
 'FiscalYear',
 'FiscalSemester',
 'Profit',
 'ProfitMargin']

In [186]:
[col for col in sales_region.columns if "Year" in col]

['DayNumberOfYear',
 'WeekNumberOfYear',
 'MonthNumberOfYear',
 'CalendarYear',
 'FiscalYear']

In [190]:
region_year_growth = (
    sales_region
    .groupby(["CalendarYear", "SalesTerritoryRegion"])
    .agg({
        "SalesAmount":"sum",
        "Profit":"sum"
    })
    .reset_index()
)
region_year_growth

    CalendarYear SalesTerritoryRegion   SalesAmount        Profit
0           2005            Australia  1.309047e+06  5.285692e+05
1           2005               Canada  1.468298e+05  5.871115e+04
2           2005               France  1.805717e+05  7.246343e+04
3           2005              Germany  2.377850e+05  9.557350e+04
4           2005            Northwest  4.152035e+05  1.659826e+05
5           2005            Southwest  6.853460e+05  2.730548e+05
6           2005       United Kingdom  2.915905e+05  1.172513e+05
7           2006            Australia  2.154285e+06  8.798600e+05
8           2006               Canada  6.216024e+05  2.477306e+05
9           2006               France  5.149420e+05  2.081840e+05
10          2006              Germany  5.212308e+05  2.103612e+05
11          2006            Northwest  8.478393e+05  3.420576e+05
12          2006            Southeast  7.829900e+02  2.962834e+02
13          2006            Southwest  1.278074e+06  5.175522e+05
14          2006       United Kingdom  5.915869e+05  2.408084e+05
15          2007            Australia  3.033784e+06  1.246320e+06
16          2007               Canada  5.357845e+05  2.329469e+05
17          2007              Central  2.768120e+03  1.226624e+03
18          2007               France  1.026325e+06  4.235803e+05
19          2007              Germany  1.058406e+06  4.330130e+05
20          2007            Northeast  3.966808e+03  1.697435e+03
21          2007            Northwest  1.094829e+06  4.667773e+05
22          2007            Southeast  3.013460e+03  1.349412e+03
23          2007            Southwest  1.733934e+06  7.332647e+05
24          2007       United Kingdom  1.298249e+06  5.325578e+05
25          2008            Australia  2.563884e+06  1.031106e+06
26          2008               Canada  6.736282e+05  2.905328e+05
27          2008              Central  2.327100e+02  1.242961e+02
28          2008               France  9.221790e+05  3.820370e+05
29          2008              Germany  1.076891e+06  4.484232e+05
30          2008            Northeast  2.565660e+03  1.205328e+03
31          2008            Northwest  1.291994e+06  5.448139e+05
32          2008            Southeast  8.442400e+03  3.686731e+03
33          2008            Southwest  2.020796e+06  8.478918e+05
34          2008       United Kingdom  1.210286e+06  4.998733e+05

In [191]:
customers.columns.tolist()

NameError: name 'customers' is not defined

In [193]:
customers = pd.read_sql("""
SELECT *
FROM DimCustomer
""", conn)

customers.head()

,CustomerKey,GeographyKey,CustomerAlternateKey,Title,FirstName,MiddleName,LastName,NameStyle,BirthDate,MaritalStatus,...,EnglishOccupation,SpanishOccupation,FrenchOccupation,HouseOwnerFlag,NumberCarsOwned,AddressLine1,AddressLine2,Phone,DateFirstPurchase,CommuteDistance
0,11000,26,AW00011000,NaN,Jon,V,Yang,False,1970-04-08,M,...,Professional,Profesional,Cadre,1,0,3761 N. 14th St,NaN,1 (11) 500 555-0162,2005-07-22,1-2 Miles
1,11001,37,AW00011001,NaN,Eugene,L,Huang,False,1969-05-14,S,...,Professional,Profesional,Cadre,0,1,2243 W St.,NaN,1 (11) 500 555-0110,2005-07-18,0-1 Miles
2,11002,31,AW00011002,NaN,Ruben,NaN,Torres,False,1969-08-12,M,...,Professional,Profesional,Cadre,1,1,5844 Linden Land,NaN,1 (11) 500 555-0184,2005-07-10,2-5 Miles
3,11003,11,AW00011003,NaN,Christy,NaN,Zhu,False,1972-02-15,S,...,Professional,Profesional,Cadre,0,1,1825 Village Pl.,NaN,1 (11) 500 555-0162,2005-07-01,5-10 Miles
4,11004,19,AW00011004,NaN,Elizabeth,NaN,Johnson,False,1972-08-08,S,...,Professional,Profesional,Cadre,1,4,7553 Harness Circle,NaN,1 (11) 500 555-0131,2005-07-26,1-2 Miles

In [194]:
customers.columns.tolist()

['CustomerKey',
 'GeographyKey',
 'CustomerAlternateKey',
 'Title',
 'FirstName',
 'MiddleName',
 'LastName',
 'NameStyle',
 'BirthDate',
 'MaritalStatus',
 'Suffix',
 'Gender',
 'EmailAddress',
 'YearlyIncome',
 'TotalChildren',
 'NumberChildrenAtHome',
 'EnglishEducation',
 'SpanishEducation',
 'FrenchEducation',
 'EnglishOccupation',
 'SpanishOccupation',
 'FrenchOccupation',
 'HouseOwnerFlag',
 'NumberCarsOwned',
 'AddressLine1',
 'AddressLine2',
 'Phone',
 'DateFirstPurchase',
 'CommuteDistance']

In [195]:
customer_sales = sales_region.merge(
    customers,
    on="CustomerKey",
    how="left"
)
customer_sales.head()

,ProductKey,OrderDateKey,DueDateKey,ShipDateKey,CustomerKey,PromotionKey,CurrencyKey,SalesTerritoryKey,SalesOrderNumber,SalesOrderLineNumber,...,EnglishOccupation,SpanishOccupation,FrenchOccupation,HouseOwnerFlag,NumberCarsOwned,AddressLine1,AddressLine2,Phone,DateFirstPurchase,CommuteDistance
0,310,20050701,20050713,20050708,21768,1,19,6,SO43697,1,...,Management,Gestión,Direction,1,3,601 Asilomar Dr.,NaN,110-555-0129,2005-07-01,10+ Miles
1,346,20050701,20050713,20050708,28389,1,39,7,SO43698,1,...,Manual,Obrero,Ouvrier,0,0,"14, avenue du Port",NaN,1 (11) 500 555-0190,2005-07-01,0-1 Miles
2,346,20050701,20050713,20050708,25863,1,100,1,SO43699,1,...,Professional,Profesional,Cadre,1,3,4193 E. 28th Street,NaN,285-555-0113,2005-07-01,10+ Miles
3,336,20050701,20050713,20050708,14501,1,100,4,SO43700,1,...,Management,Gestión,Direction,1,2,249 Alexander Pl.,NaN,175-555-0159,2005-07-01,1-2 Miles
4,346,20050701,20050713,20050708,11003,1,6,9,SO43701,1,...,Professional,Profesional,Cadre,0,1,1825 Village Pl.,NaN,1 (11) 500 555-0162,2005-07-01,5-10 Miles

In [196]:
customer_sales.shape

(60398, 76)

In [197]:
customer_sales[[
    "CustomerKey",
    "SalesAmount",
    "Profit",
    "Gender",
    "EnglishOccupation"
]].head()

   CustomerKey  SalesAmount     Profit Gender EnglishOccupation
0        21768    3578.2700  1406.9758      M        Management
1        28389    3399.9900  1487.8356      F            Manual
2        25863    3399.9900  1487.8356      F      Professional
3        14501     699.0982   285.9519      M        Management
4        11003    3399.9900  1487.8356      F      Professional

In [200]:
top_customers = (
    customer_sales
    .groupby("CustomerKey")
    .agg({
        "SalesAmount":"sum",
        "Profit":"sum",
        "SalesOrderNumber":"nunique"
    })
    .reset_index()
    .sort_values("SalesAmount", ascending=False)
)
top_customers.head()

      CustomerKey  SalesAmount     Profit  SalesOrderNumber
1301        12301     13295.38  5250.4207                 5
1132        12132     13294.27  5273.8100                 5
1308        12308     13269.27  5254.6000                 5
1131        12131     13265.99  5232.0226                 5
1300        12300     13242.70  5237.2391                 5

In [201]:
top_customers_named = (
    customer_sales
    .groupby([
        "CustomerKey",
        "FirstName",
        "LastName",
        "EnglishOccupation",
        "YearlyIncome"
    ])
    .agg({
        "SalesAmount":"sum",
        "Profit":"sum",
        "SalesOrderNumber":"nunique"
    })
    .reset_index()
    .sort_values("SalesAmount", ascending=False)
)

top_customers_named.head(10)

,CustomerKey,FirstName,LastName,EnglishOccupation,YearlyIncome,SalesAmount,Profit,SalesOrderNumber
1301,12301,Nichole,Nara,Management,100000.0,13295.3800,5250.4207,5
1132,12132,Kaitlyn,Henderson,Professional,110000.0,13294.2700,5273.8100,5
1308,12308,Margaret,He,Professional,100000.0,13269.2700,5254.6000,5
1131,12131,Randall,Dominguez,Professional,90000.0,13265.9900,5232.0226,5
1300,12300,Adriana,Gonzalez,Professional,80000.0,13242.7000,5237.2391,5
1321,12321,Rosa,Hu,Skilled Manual,70000.0,13215.6500,5221.0338,5
1124,12124,Brandi,Gill,Professional,110000.0,13195.6400,5208.5077,5
1307,12307,Brad,She,Professional,90000.0,13173.1900,5198.0140,5
1296,12296,Francisco,Sara,Professional,70000.0,13164.6400,5189.1017,5
433,11433,Maurice,Shan,Professional,80000.0,12909.6682,5196.5982,6

In [202]:
top_customers_named["AvgOrderValue"] = (
    top_customers_named["SalesAmount"]
    / top_customers_named["SalesOrderNumber"]
)

top_customers_named.head(10)

,CustomerKey,FirstName,LastName,EnglishOccupation,YearlyIncome,SalesAmount,Profit,SalesOrderNumber,AvgOrderValue
1301,12301,Nichole,Nara,Management,100000.0,13295.3800,5250.4207,5,2659.076000
1132,12132,Kaitlyn,Henderson,Professional,110000.0,13294.2700,5273.8100,5,2658.854000
1308,12308,Margaret,He,Professional,100000.0,13269.2700,5254.6000,5,2653.854000
1131,12131,Randall,Dominguez,Professional,90000.0,13265.9900,5232.0226,5,2653.198000
1300,12300,Adriana,Gonzalez,Professional,80000.0,13242.7000,5237.2391,5,2648.540000
1321,12321,Rosa,Hu,Skilled Manual,70000.0,13215.6500,5221.0338,5,2643.130000
1124,12124,Brandi,Gill,Professional,110000.0,13195.6400,5208.5077,5,2639.128000
1307,12307,Brad,She,Professional,90000.0,13173.1900,5198.0140,5,2634.638000
1296,12296,Francisco,Sara,Professional,70000.0,13164.6400,5189.1017,5,2632.928000
433,11433,Maurice,Shan,Professional,80000.0,12909.6682,5196.5982,6,2151.611367

In [203]:
occupation_performance = (
    customer_sales
    .groupby("EnglishOccupation")
    .agg({
        "SalesAmount":"sum",
        "Profit":"sum",
        "CustomerKey":"nunique",
        "SalesOrderNumber":"nunique"
    })
    .reset_index()
    .sort_values("SalesAmount", ascending=False)
)

occupation_performance

  EnglishOccupation   SalesAmount        Profit  CustomerKey  SalesOrderNumber
3      Professional  9.907977e+06  4.099568e+06         5520              8661
4    Skilled Manual  6.440081e+06  2.640524e+06         4577              6599
1        Management  5.467862e+06  2.260335e+06         3075              4819
0          Clerical  4.684787e+06  1.910436e+06         2928              4398
2            Manual  2.857971e+06  1.170020e+06         2384              3182

In [204]:
occupation_performance["RevenuePerCustomer"] = (
    occupation_performance["SalesAmount"]
    / occupation_performance["CustomerKey"]
)

occupation_performance["ProfitPerCustomer"] = (
    occupation_performance["Profit"]
    / occupation_performance["CustomerKey"]
)

occupation_performance.sort_values(
    "RevenuePerCustomer",
    ascending=False
)

,EnglishOccupation,SalesAmount,Profit,CustomerKey,SalesOrderNumber,RevenuePerCustomer,ProfitPerCustomer
3,Professional,9.907977e+06,4.099568e+06,5520,8661,1794.923420,742.675433
1,Management,5.467862e+06,2.260335e+06,3075,4819,1778.166356,735.068249
0,Clerical,4.684787e+06,1.910436e+06,2928,4398,1599.995438,652.471380
4,Skilled Manual,6.440081e+06,2.640524e+06,4577,6599,1407.052842,576.911460
2,Manual,2.857971e+06,1.170020e+06,2384,3182,1198.813294,490.780385

In [206]:
customer_sales["Age"].sort_values().head(20)

KeyError: 'Age'

In [207]:
customer_sales["BirthDate"] = pd.to_datetime(customer_sales["BirthDate"])
                                             
customer_sales["Age"] = (
    customer_sales["CalendarYear"]
     - customer_sales["BirthDate"].dt.year
)
customer_sales["Age"].describe()

count    60398.000000
mean        41.804000
std         11.074607
min         21.000000
25%         33.000000
50%         40.000000
75%         49.000000
max         94.000000
Name: Age, dtype: float64

In [208]:
customer_sales["YearlyIncome"].describe()

count     60398.000000
mean      59715.056790
std       33065.426837
min       10000.000000
25%       30000.000000
50%       60000.000000
75%       80000.000000
max      170000.000000
Name: YearlyIncome, dtype: float64

In [209]:
customer_sales["AgeGroup"] = pd.cut(
    customer_sales["Age"],
    bins=[20, 29, 39, 49, 59, 100],
    labels=[
        "21-29",
        "30-39",
        "40-49",
        "50-59",
        "60+"
    ]
)

In [210]:
age_performance = (
    customer_sales
    .groupby("AgeGroup")
    .agg({
        "SalesAmount": "sum",
        "Profit": "sum",
        "CustomerKey": "nunique",
        "SalesOrderNumber": "nunique"
    })
    .reset_index()
)

age_performance

  AgeGroup   SalesAmount        Profit  CustomerKey  SalesOrderNumber
0    21-29  3.655496e+06  1.498954e+06         2752              3821
1    30-39  1.134641e+07  4.647500e+06         6413              9521
2    40-49  8.822168e+06  3.632398e+06         5492              7947
3    50-59  4.104300e+06  1.701425e+06         3138              4345
4      60+  1.430306e+06  6.006065e+05         1524              2025

In [211]:
age_performance["RevenuePerCustomer"] = (
    age_performance["SalesAmount"]
    / age_performance["CustomerKey"]
)

age_performance["ProfitPerCustomer"] = (
    age_performance["Profit"]
    / age_performance["CustomerKey"]
)

age_performance.sort_values(
    "RevenuePerCustomer",
    ascending=False
)

,AgeGroup,SalesAmount,Profit,CustomerKey,SalesOrderNumber,RevenuePerCustomer,ProfitPerCustomer
1,30-39,1.134641e+07,4.647500e+06,6413,9521,1769.282261,724.699837
2,40-49,8.822168e+06,3.632398e+06,5492,7947,1606.367083,661.398048
0,21-29,3.655496e+06,1.498954e+06,2752,3821,1328.305070,544.678050
3,50-59,4.104300e+06,1.701425e+06,3138,4345,1307.935143,542.200454
4,60+,1.430306e+06,6.006065e+05,1524,2025,938.521017,394.098749

In [212]:
age_performance["RevenuePerCustomer"] = (
    age_performance["SalesAmount"]
    / age_performance["CustomerKey"]
)

age_performance["ProfitPerCustomer"] = (
    age_performance["Profit"]
    / age_performance["CustomerKey"]
)

age_performance.sort_values(
    "RevenuePerCustomer",
    ascending=False
)

,AgeGroup,SalesAmount,Profit,CustomerKey,SalesOrderNumber,RevenuePerCustomer,ProfitPerCustomer
1,30-39,1.134641e+07,4.647500e+06,6413,9521,1769.282261,724.699837
2,40-49,8.822168e+06,3.632398e+06,5492,7947,1606.367083,661.398048
0,21-29,3.655496e+06,1.498954e+06,2752,3821,1328.305070,544.678050
3,50-59,4.104300e+06,1.701425e+06,3138,4345,1307.935143,542.200454
4,60+,1.430306e+06,6.006065e+05,1524,2025,938.521017,394.098749

In [213]:
customer_sales["IncomeGroup"] = pd.cut(
    customer_sales["YearlyIncome"],
    bins=[0, 30000, 60000, 90000, 120000, 200000],
    labels=[
        "Low Income (<30K)",
        "Lower-Middle (30K-60K)",
        "Middle (60K-90K)",
        "Upper-Middle (90K-120K)",
        "High Income (120K+)"
    ]
)

In [214]:
customer_sales["IncomeGroup"].value_counts().sort_index()

IncomeGroup
Low Income (<30K)          15474
Lower-Middle (30K-60K)     20628
Middle (60K-90K)           16258
Upper-Middle (90K-120K)     4912
High Income (120K+)         3126
Name: count, dtype: int64

In [215]:
income_performance = (
    customer_sales
    .groupby("IncomeGroup")
    .agg({
        "SalesAmount": "sum",
        "Profit": "sum",
        "CustomerKey": "nunique",
        "SalesOrderNumber": "nunique"
    })
    .reset_index()
)

income_performance

,IncomeGroup,SalesAmount,Profit,CustomerKey,SalesOrderNumber
0,Low Income (<30K),6.329285e+06,2.581793e+06,5209,7161
1,Lower-Middle (30K-60K),9.262665e+06,3.784977e+06,6544,9452
2,Middle (60K-90K),8.942758e+06,3.719039e+06,4533,7418
3,Upper-Middle (90K-120K),2.853162e+06,1.174811e+06,1377,2260
4,High Income (120K+),1.970807e+06,8.202632e+05,821,1368

In [216]:
income_performance["RevenuePerCustomer"] = (
    income_performance["SalesAmount"]
    / income_performance["CustomerKey"]
)

income_performance["ProfitPerCustomer"] = (
    income_performance["Profit"]
    / income_performance["CustomerKey"]
)

income_performance.sort_values(
    "RevenuePerCustomer",
    ascending=False
)

,IncomeGroup,SalesAmount,Profit,CustomerKey,SalesOrderNumber,RevenuePerCustomer,ProfitPerCustomer
4,High Income (120K+),1.970807e+06,8.202632e+05,821,1368,2400.496127,999.102590
3,Upper-Middle (90K-120K),2.853162e+06,1.174811e+06,1377,2260,2072.013033,853.167242
2,Middle (60K-90K),8.942758e+06,3.719039e+06,4533,7418,1972.812330,820.436605
1,Lower-Middle (30K-60K),9.262665e+06,3.784977e+06,6544,9452,1415.443901,578.388899
0,Low Income (<30K),6.329285e+06,2.581793e+06,5209,7161,1215.067148,495.640821

In [217]:
gender_performance = (
    customer_sales
    .groupby("Gender")
    .agg({
        "SalesAmount":"sum",
        "Profit":"sum",
        "CustomerKey":"nunique",
        "SalesOrderNumber":"nunique"

    })
    .reset_index()
)
gender_performance

  Gender   SalesAmount        Profit  CustomerKey  SalesOrderNumber
0      F  1.481362e+07  6.098442e+06         9133             13742
1      M  1.454506e+07  5.982442e+06         9351             13917

In [218]:
gender_performance["RevenuePerCustomer"] = (
    gender_performance["SalesAmount"]
    / gender_performance["CustomerKey"]
)

gender_performance["ProfitPerCustomer"] = (
    gender_performance["Profit"]
    / gender_performance["CustomerKey"]
)

gender_performance.sort_values(
    "RevenuePerCustomer",
    ascending=False
)

,Gender,SalesAmount,Profit,CustomerKey,SalesOrderNumber,RevenuePerCustomer,ProfitPerCustomer
0,F,1.481362e+07,6.098442e+06,9133,13742,1621.988249,667.736962
1,M,1.454506e+07,5.982442e+06,9351,13917,1555.454876,639.764942

In [219]:
income_behavior = (
    customer_sales
    .groupby("IncomeGroup")
    .agg({
        "SalesAmount":"sum",
        "SalesOrderNumber":"nunique",
        "CustomerKey":"nunique"
    })
    .reset_index()
)

income_behavior["AvgOrderValue"] = (
    income_behavior["SalesAmount"]
    / income_behavior["SalesOrderNumber"]
)

income_behavior["PurchaseFrequency"] = (
    income_behavior["SalesOrderNumber"]
    / income_behavior["CustomerKey"]
)

income_behavior.sort_values(
    "AvgOrderValue",
    ascending=False
)

,IncomeGroup,SalesAmount,SalesOrderNumber,CustomerKey,AvgOrderValue,PurchaseFrequency
4,High Income (120K+),1.970807e+06,1368,821,1440.648626,1.666261
3,Upper-Middle (90K-120K),2.853162e+06,2260,1377,1262.461038,1.641249
2,Middle (60K-90K),8.942758e+06,7418,4533,1205.548435,1.636444
1,Lower-Middle (30K-60K),9.262665e+06,9452,6544,979.968778,1.444377
0,Low Income (<30K),6.329285e+06,7161,5209,883.854877,1.374736

In [220]:
age_behavior = (
    customer_sales
    .groupby("AgeGroup")
    .agg({
        "SalesAmount":"sum",
        "SalesOrderNumber":"nunique",
        "CustomerKey":"nunique"
    })
    .reset_index()
)

age_behavior["AvgOrderValue"] = (
    age_behavior["SalesAmount"]
    / age_behavior["SalesOrderNumber"]
)

age_behavior["PurchaseFrequency"] = (
    age_behavior["SalesOrderNumber"]
    / age_behavior["CustomerKey"]
)

age_behavior.sort_values(
    "AvgOrderValue",
    ascending=False
)

,AgeGroup,SalesAmount,SalesOrderNumber,CustomerKey,AvgOrderValue,PurchaseFrequency
1,30-39,1.134641e+07,9521,6413,1191.724308,1.484641
2,40-49,8.822168e+06,7947,5492,1110.125585,1.447014
0,21-29,3.655496e+06,3821,2752,956.685567,1.388445
3,50-59,4.104300e+06,4345,3138,944.603102,1.384640
4,60+,1.430306e+06,2025,1524,706.323965,1.328740

In [221]:
occupation_behavior = (
    customer_sales
    .groupby("EnglishOccupation")
    .agg({
        "SalesAmount":"sum",
        "Profit":"sum",
        "CustomerKey":"nunique",
        "SalesOrderNumber":"nunique"
    })
    .reset_index()
)

occupation_behavior["RevenuePerCustomer"] = (
    occupation_behavior["SalesAmount"]
    / occupation_behavior["CustomerKey"]
)

occupation_behavior["ProfitPerCustomer"] = (
    occupation_behavior["Profit"]
    / occupation_behavior["CustomerKey"]
)

occupation_behavior["PurchaseFrequency"] = (
    occupation_behavior["SalesOrderNumber"]
    / occupation_behavior["CustomerKey"]
)

occupation_behavior.sort_values(
    "RevenuePerCustomer",
    ascending=False
)

,EnglishOccupation,SalesAmount,Profit,CustomerKey,SalesOrderNumber,RevenuePerCustomer,ProfitPerCustomer,PurchaseFrequency
3,Professional,9.907977e+06,4.099568e+06,5520,8661,1794.923420,742.675433,1.569022
1,Management,5.467862e+06,2.260335e+06,3075,4819,1778.166356,735.068249,1.567154
0,Clerical,4.684787e+06,1.910436e+06,2928,4398,1599.995438,652.471380,1.502049
4,Skilled Manual,6.440081e+06,2.640524e+06,4577,6599,1407.052842,576.911460,1.441774
2,Manual,2.857971e+06,1.170020e+06,2384,3182,1198.813294,490.780385,1.334732

In [225]:
for name in dataframes.keys(): 
    print(name)

NameError: name 'dataframes' is not defined

In [228]:
employees = pd.read_sql("""
SELECT *
FROM DimEmployee
""", conn)

reseller_sales = pd.read_sql("""
SELECT *
FROM FactResellerSales
""", conn)

sales_quota = pd.read_sql("""
SELECT *
FROM FactSalesQuota
""", conn)

territories = pd.read_sql("""
SELECT *
FROM DimSalesTerritory
""", conn)

DatabaseError: Execution failed on sql '
SELECT *
FROM DimEmployee
': no such table: DimEmployee

In [ ]:
region_category_performance = (
    sales_product_category
    .groupby(["SalesTerritoryRegion", "EnglishProductCategoryName"])
    .agg({
        "SalesAmount":"sum",
        "Profit":"sum"
    })
    .reset_index()
    .sort_values("SalesAmount", ascending=False)
)
region_category_performance.head(20)

KeyError: 'SalesTerritoryRegion'

In [229]:
employees = pd.read_sql("""
SELECT *
FROM DimEmployee
""", conn)

reseller_sales = pd.read_sql("""
SELECT *
FROM FactResellerSales
""", conn)

sales_quota = pd.read_sql("""
SELECT *
FROM FactSalesQuota
""", conn)

territories = pd.read_sql("""
SELECT *
FROM DimSalesTerritory
""", conn)

DatabaseError: Execution failed on sql '
SELECT *
FROM DimEmployee
': no such table: DimEmployee

In [230]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
ORDER BY name
""", conn)

                     name
0              DimAccount
1             DimCustomer
2                 DimDate
3            DimGeography
4              DimProduct
5      DimProductCategory
6   DimProductSubcategory
7       DimSalesTerritory
8             DimScenario
9             FactFinance
10      FactInternetSales
11         FactSalesQuota

In [231]:
pd.read_sql("""
PRAGMA database_list;
""", conn)

   seq  name                                               file
0    0  main  /Users/bibi/AdventureWorks Financial Analysis/...

In [232]:
import sqlite3
conn.close()
conn = sqlite3.connect("/Users/bibi/Downloads/adventureworks_financial_analysis.db")

In [234]:
pd.read_sql(""" 
SELECT name
FROM sqlite_master
WHERE type='table' 
ORDER BY name
""", conn)

                     name
0              DimAccount
1             DimCustomer
2                 DimDate
3             DimEmployee
4            DimGeography
5              DimProduct
6      DimProductCategory
7   DimProductSubcategory
8       DimSalesTerritory
9             DimScenario
10            FactFinance
11      FactInternetSales
12      FactResellerSales
13         FactSalesQuota

In [235]:
employees = pd.read_sql("""
SELECT *
FROM DimEmployee
""", conn)

reseller_sales = pd.read_sql("""
SELECT *
FROM FactResellerSales
""", conn)

sales_quota = pd.read_sql("""
SELECT *
FROM FactSalesQuota
""", conn)

territories = pd.read_sql("""
SELECT *
FROM DimSalesTerritory
""", conn)

In [238]:
employees.shape,
reseller_sales.shape,
sales_quota.shape,
territories.shape

(11, 5)

In [239]:
print("employees:", employees.shape)
print("reseller_sales:", reseller_sales.shape)
print("sales_quota:", sales_quota.shape)
print("territories:", territories.shape)

employees: (296, 30)
reseller_sales: (60855, 24)
sales_quota: (163, 6)
territories: (11, 5)

In [240]:
employees.columns

Index(['EmployeeKey', 'ParentEmployeeKey', 'EmployeeNationalIDAlternateKey',
       'ParentEmployeeNationalIDAlternateKey', 'SalesTerritoryKey',
       'FirstName', 'LastName', 'MiddleName', 'NameStyle', 'Title', 'HireDate',
       'BirthDate', 'LoginID', 'EmailAddress', 'Phone', 'MaritalStatus',
       'EmergencyContactName', 'EmergencyContactPhone', 'SalariedFlag',
       'Gender', 'PayFrequency', 'BaseRate', 'VacationHours', 'SickLeaveHours',
       'CurrentFlag', 'SalesPersonFlag', 'DepartmentName', 'StartDate',
       'EndDate', 'Status'],
      dtype='str')

In [241]:
reseller_sales.columns

Index(['ProductKey', 'OrderDateKey', 'DueDateKey', 'ShipDateKey',
       'ResellerKey', 'EmployeeKey', 'PromotionKey', 'CurrencyKey',
       'SalesTerritoryKey', 'SalesOrderNumber', 'SalesOrderLineNumber',
       'RevisionNumber', 'OrderQuantity', 'UnitPrice', 'ExtendedAmount',
       'UnitPriceDiscountPct', 'DiscountAmount', 'ProductStandardCost',
       'TotalProductCost', 'SalesAmount', 'TaxAmt', 'Freight',
       'CarrierTrackingNumber', 'CustomerPONumber'],
      dtype='str')

In [242]:
sales_quota.columns

Index(['SalesQuotaKey', 'EmployeeKey', 'DateKey', 'CalendarYear',
       'CalendarQuarter', 'SalesAmountQuota'],
      dtype='str')

In [243]:
territories.columns

Index(['SalesTerritoryKey', 'SalesTerritoryAlternateKey',
       'SalesTerritoryRegion', 'SalesTerritoryCountry', 'SalesTerritoryGroup'],
      dtype='str')

In [244]:
sales_quota.head()

,SalesQuotaKey,EmployeeKey,DateKey,CalendarYear,CalendarQuarter,SalesAmountQuota
0,1,272,20050701,2005,3,28000.0
1,2,281,20050701,2005,3,367000.0
2,3,282,20050701,2005,3,637000.0
3,4,283,20050701,2005,3,565000.0
4,5,284,20050701,2005,3,244000.0

In [245]:
sales_quota.describe()

,SalesQuotaKey,EmployeeKey,DateKey,CalendarYear,CalendarQuarter,SalesAmountQuota
count,163.000000,163.000000,1.630000e+02,163.000000,163.000000,1.630000e+02
mean,82.000000,286.006135,2.006730e+07,2006.674847,2.496933,5.872025e+05
std,47.198164,5.621275,9.264674e+03,0.942046,1.124224,3.984506e+05
min,1.000000,272.000000,2.005070e+07,2005.000000,1.000000,1.000000e+03
25%,41.500000,283.000000,2.006070e+07,2006.000000,1.500000,2.825000e+05
50%,82.000000,286.000000,2.007040e+07,2007.000000,2.000000,5.070000e+05
75%,122.500000,290.000000,2.007100e+07,2007.000000,3.500000,8.345000e+05
max,163.000000,296.000000,2.008040e+07,2008.000000,4.000000,1.898000e+06

In [247]:
reseller_sales[['OrderDateKey']].head()

   OrderDateKey
0      20050701
1      20050701
2      20050701
3      20050701
4      20050701

In [248]:
reseller_sales['OrderDateKey'].describe()

count    6.085500e+04
mean     2.006878e+07
std      8.378159e+03
min      2.005070e+07
25%      2.006090e+07
50%      2.007070e+07
75%      2.007120e+07
max      2.008060e+07
Name: OrderDateKey, dtype: float64

In [250]:
pd.set_option('display.max_columns', None)
date_table = pd.read_sql(""" 
SELECT *
FROM DimDate
LIMIT 5
""", conn)
date_table

,DateKey,FullDateAlternateKey,DayNumberOfWeek,EnglishDayNameOfWeek,SpanishDayNameOfWeek,FrenchDayNameOfWeek,DayNumberOfMonth,DayNumberOfYear,WeekNumberOfYear,EnglishMonthName,SpanishMonthName,FrenchMonthName,MonthNumberOfYear,CalendarQuarter,CalendarYear,CalendarSemester,FiscalQuarter,FiscalYear,FiscalSemester
0,20050701,2005-07-01,6,Friday,Viernes,Vendredi,1,182,27,July,Julio,Juillet,7,3,2005,2,1,2006,1
1,20050702,2005-07-02,7,Saturday,Sábado,Samedi,2,183,27,July,Julio,Juillet,7,3,2005,2,1,2006,1
2,20050703,2005-07-03,1,Sunday,Domingo,Dimanche,3,184,27,July,Julio,Juillet,7,3,2005,2,1,2006,1
3,20050704,2005-07-04,2,Monday,Lunes,Lundi,4,185,27,July,Julio,Juillet,7,3,2005,2,1,2006,1
4,20050705,2005-07-05,3,Tuesday,Martes,Mardi,5,186,27,July,Julio,Juillet,7,3,2005,2,1,2006,1

In [251]:
sales_with_dates = reseller_sales.merge(
    date_table[['DateKey', 'CalendarYear', 'CalendarQuarter']],
    left_on='OrderDateKey',
    right_on='DateKey',
    how='left'
)

sales_summary = (
    sales_with_dates
    .groupby(
        ['EmployeeKey', 'CalendarYear', 'CalendarQuarter'],
        as_index=False
    )['SalesAmount']
    .sum()
)

sales_summary.head()

   EmployeeKey  CalendarYear  CalendarQuarter  SalesAmount
0          281        2005.0              3.0   63762.9228
1          282        2005.0              3.0    5475.9485
2          283        2005.0              3.0   46695.5564
3          284        2005.0              3.0    9109.1683
4          285        2005.0              3.0  104419.3291

In [252]:
quota_vs_sales = sales_quota.merge(
    sales_summary,
    on=['EmployeeKey', 'CalendarYear', 'CalendarQuarter'],
    how='left'
)

quota_vs_sales.head()

,SalesQuotaKey,EmployeeKey,DateKey,CalendarYear,CalendarQuarter,SalesAmountQuota,SalesAmount
0,1,272,20050701,2005,3,28000.0,NaN
1,2,281,20050701,2005,3,367000.0,63762.9228
2,3,282,20050701,2005,3,637000.0,5475.9485
3,4,283,20050701,2005,3,565000.0,46695.5564
4,5,284,20050701,2005,3,244000.0,9109.1683

In [253]:
quota_vs_sales.shape

(163, 7)

In [254]:
quota_vs_sales.isnull().sum()

SalesQuotaKey         0
EmployeeKey           0
DateKey               0
CalendarYear          0
CalendarQuarter       0
SalesAmountQuota      0
SalesAmount         154
dtype: int64